Rough First Draft
NMDSdevopsServiceAdm/DataEngineering pull request #17
Opened 2022-02-14 09:37 UTC by AnthonyWheatley

Rough first draft for wording to be reviewed, to be formatted correctly.
Circle ci is the only tool I have not used yet so I have left this blank for now until I have a better understanding.

2022-02-14 10:00 UTC, AdamProbert requested changes
Great start! I've added a shed load of comments :)
I'd also add a section about Git.

2022-02-16 10:39 UTC, AdamProbert requested changes
Looks like you've resolved a lot of the suggestions I made - there's still quite a few here though. Happy to hear your opinion on them :)

2022-02-16 10:39 UTC, AdamProbert commented on Glossaryoftools.md
> +Jupyter is not used for programming applications as this is more of a research/development environment however, it can be good to use jupyer if you want to analys1e some data without turning it into
```suggestion
Jupyter is not used for programming applications as this is more of a research/development environment however, it can be good to use Jupyter if you want to analyse some data or experiment with modelling without the overhead of a glue job.
```

2022-02-28 15:32 UTC, AdamProbert approved these changes
Nice work!

2022-03-01 13:05 UTC, garypolzin approved these changes
Happy with all of this, looks good

2022-03-02 11:06 UTC, merged