Rolling average for all locations, split by primary service
NMDSdevopsServiceAdm/DataEngineering pull request #183
Opened 2023-04-03 14:03 UTC by garypolzin

Creates a rolling average column in estimated jobs for every location, split by primary service type

Need to double check it's looking ok in tableau prior to merging

[Trello ticket](https://trello.com/c/RBejz9ta/109-make-rolling-average-code-more-efficient)

2023-04-25 15:45 UTC, MarionJHolloway requested changes
Looks good! - just a few points I spotted that need tidying up

2023-04-25 15:45 UTC, MarionJHolloway commented on jobs/estimate_job_counts.py
> +NUMBER_OF_DAYS_IN_ROLLING_AVERAGE = 88
I like that you moved this into estimate job counts - much easier to edit if needed

2023-04-25 15:45 UTC, MarionJHolloway commented on utils/estimate_job_count/models/primary_service_rolling_average.py
> +def calculate_job_count_sum_and_count_per_service_and_time_period(
I would recommend refactoring this. Functions should do one thing. That makes them easier to modify later down the line. I would either separate this into a function for each variable, or create sub-functions within it for each variable and then use this as a "put it all together" kind of function.

2023-04-25 15:45 UTC, MarionJHolloway commented on utils/estimate_job_count/models/primary_service_rolling_average.py
> +from utils.estimate_job_count.column_names import (
I think we could do with extracting the columns used in creating the rolling average as well - there's a few magic strings in here that are reused within this script

2023-04-25 15:45 UTC, MarionJHolloway commented on utils/estimate_job_count/models/primary_service_rolling_average.py
> +def rolling_average_time_period(unix_date_col: str, number_of_days: int):
1) need to specify return type here
2) rename as something like "calculate_rolling_average_time_period"

2023-04-25 15:45 UTC, MarionJHolloway commented on utils/utils.py
> +    return days * 86400
Refactor to remove magic number

2023-04-26 07:37 UTC, garypolzin commented on tests/unit/test_utils.py
> +    def test_convert_days_to_unix_time(self):
this one is a bit different - we type the number of days to be used in the rolling average calculation but the calculation itself needs it in unix time, so it's just the numerical input

rangeBetween(-convert_days_to_unix_time(number_of_days), 0)

2023-04-26 08:00 UTC, garypolzin commented on utils/estimate_job_count/models/primary_service_rolling_average.py
> +def calculate_job_count_sum_and_count_per_service_and_time_period(
hmm, it's only doing one aggregation so in that sense it's only doing one thing? Seems overkill and more at risk of them becoming out of sync to do the same aggregation function separately twice, once for sum and once for count, then joining them together?

I tend to worry less about functions which we haven't created ourselves, groupBy/agg/sum/count are all standard and will be fully tested as they are, so we can trust that they work as expected a lot more than a self written function

2023-04-26 08:26 UTC, garypolzin commented on utils/estimate_job_count/models/primary_service_rolling_average.py
> +def rolling_average_time_period(unix_date_col: str, number_of_days: int):
this returns the window to be used in the calculation, not sure what type that is!

I've renamed to "define_window_specifications"

2023-04-26 08:38 UTC, garypolzin commented on tests/unit/test_model_primary_service_rolling_average.py
> +    def test_join_rolling_average_into_df(self):
Need a hand with this, can't figure out how to do it!

2023-04-26 08:48 UTC, garypolzin commented on utils/estimate_job_count/models/primary_service_rolling_average.py
> +from utils.estimate_job_count.column_names import (
Created a dataclass for these

2023-05-05 10:25 UTC, garypolzin commented on utils/estimate_job_count/models/primary_service_rolling_average.py
> +def calculate_job_count_sum_and_count_per_service_and_time_period(
rename to calculate_job_count_aggregates_per_service_and_time_period

2023-05-05 10:25 UTC, garypolzin commented on tests/unit/test_model_primary_service_rolling_average.py
> +    def test_join_rolling_average_into_df(self):
check 88 is 88

2023-05-05 11:23 UTC, MarionJHolloway approved these changes
Looks good, thanks

2023-05-05 11:23 UTC, merged