Create direct payment pipeline
NMDSdevopsServiceAdm/DataEngineering pull request #199
Opened 2023-07-07 13:38 UTC by MarionJHolloway

# Description
Version 1 of the direct payments pipeline

# How to test
All tests re passing and new values signed off. 
Rolling average matches Excel/ SPSS data

# Developer checklist
- [ ] Unit test
- [ ] Linked to Trello ticket
- [ ] Documentation up to date

2023-07-10 14:46 UTC, garypolzin requested changes
Excellent work!
Most comments relate to tests (unsurprisingly as we know the code works) but some magic numbers/years are in there too

2023-07-10 14:46 UTC, garypolzin commented on tests/unit/test_dpr_remove_outliers.py
> +            ("area_5", 2022, None, Values.RETAIN),
only minor but you can make the test slightly less long by removing area_5
in terms of checks passing/failing it's identical to area_4

2023-07-10 14:46 UTC, garypolzin commented on utils/direct_payments_utils/estimate_direct_payments/estimate_service_users_employing_staff.py
> +    direct_payments_df = apply_interpolated_values(direct_payments_df)
is it correct that we interpolate, apply mean estimates, then interpolate again?
I feel like the 2nd interpolate isn't doing anything, as any remaining unknown values will have been populated with the mean_estimates

2023-07-10 14:46 UTC, garypolzin commented on utils/direct_payments_utils/prepare_direct_payments/remove_outliers.py
> +import pyspark.sql.functions as F
there are a lot of magic numbers in this job, both specific years or numerical cutoffs

can the most recent year be an argument in the job? and then
penultimate_year = most_recent_year - 1

and then have the various cutoffs kept together in a dataclass?

2023-07-11 15:17 UTC, MarionJHolloway commented on jobs/estimate_direct_payments.py
This could be useful, but we already had the logic for which model to use when - could be useful for future updates/ bug fixing though so I will add a ticket on trello.

2023-07-20 10:21 UTC, closed without merging