Extrapolation gp
NMDSdevopsServiceAdm/DataEngineering pull request #209
Opened 2023-10-27 12:07 UTC by garypolzin

Extrapolate values before/after first/last known job_counts and input as a step into estimate_job_count process

[Trello ticket](https://trello.com/c/5idvj8YB/62-extrapolation-model-to-check)

2023-10-27 15:03 UTC, MarionJHolloway reviewed
Looking good - nearly there!

2023-10-27 15:03 UTC, MarionJHolloway commented on tests/unit/test_extrapolation.py
> +    def test_model_extrapolation_row_count_unchanged(self):
As with the interpolation, it might be worth adding an integrated test of the whole of model_extrapolation()

2023-10-30 15:11 UTC, garypolzin commented on utils/estimate_job_count/models/extrapolation.py
> +def filter_to_known_values_only(
yea this was intentional - it should never have actual 0 staff if it's an open location. Even if it's dormant someone will still need to be in charge

2023-10-30 15:26 UTC, garypolzin commented on utils/estimate_job_count/models/extrapolation.py
> +    return df.withColumn(
yep, think I've done that now

2023-10-30 15:35 UTC, garypolzin commented on tests/unit/test_extrapolation.py
> +    def test_model_extrapolation_row_count_unchanged(self):
done :)

2023-10-30 15:49 UTC, garypolzin commented on utils/estimate_job_count/models/extrapolation.py
> +    for_extrapolation = add_job_count_and_rolling_average_for_first_and_last_submission(
renamed files to hopefully be more descriptive

2023-10-31 09:31 UTC, MarionJHolloway requested changes
Looking really good, just a couple of small tweaks I spotted. Be careful when you fold functions into return statements that you don't obfuscate what datatype(s) you are actually returning! It helps to be able to understand the inputs and outputs of function definitions at a glance when you come to edit the code later down the line.

2023-10-31 09:31 UTC, MarionJHolloway commented on utils/estimate_job_count/models/extrapolation.py
> +    return update_dataframe_with_identifying_rule(
Can we separate out the return statement here? It's not immediately clear what the "update dataframe..." function returns, so it masks what model_extrapolation is returning.

2023-10-31 09:31 UTC, MarionJHolloway commented on utils/estimate_job_count/models/extrapolation.py
> +    return df_with_extrapolation_ratio_column_df
This variable name has df in it twice. Can probably remove one of them

2023-10-31 09:37 UTC, garypolzin commented on utils/estimate_job_count/models/extrapolation.py
> +    return df_with_extrapolation_ratio_column_df
sorted

2023-10-31 09:40 UTC, garypolzin commented on utils/estimate_job_count/models/extrapolation.py
> +    return update_dataframe_with_identifying_rule(
thanks, will do

2023-10-31 09:46 UTC, MarionJHolloway approved these changes
Looks good to me :)

2023-10-31 09:49 UTC, merged