Upload capacity tracker data
NMDSdevopsServiceAdm/DataEngineering pull request #212
Opened 2023-11-21 13:42 UTC by MarionJHolloway

# Description
A script to import care home and non-residential capacity tracker csv files to two parquet datasets.

# How to test
Unit tests passing
Run in branch - behaving as expected

# Developer checklist
- [ ] Unit test
- [ ] Linked to Trello ticket
- [ ] Documentation up to date

2023-11-21 14:58 UTC, garypolzin requested changes
nice, neat and easy to follow but I think the auto generation of the destination will be advantageous if we plan to do this frequently. If it's going to be fairly infrequent then you could argue we don't need it

2023-11-21 14:58 UTC, garypolzin commented on jobs/ingest_capacity_tracker_data.py
> +def add_column_with_formatted_dates(df, old_column, date_format):
change old_column to be more descriptive, the function above has date_column_name which would work

2023-11-21 14:58 UTC, garypolzin commented on jobs/ingest_capacity_tracker_data.py
> +def main(care_home_source, care_home_destination, non_res_source, non_res_destination):
are you able to replicate the destination path from another job, such as ingest_cqc_pir_data
that job automatically constructs the destination file path

2023-11-21 15:31 UTC, MarionJHolloway commented
I've made the requested changes. Everything is running happily in branch.

2023-11-23 09:14 UTC, garypolzin approved these changes

2023-11-23 09:28 UTC, merged