Estimate iepa ratios
NMDSdevopsServiceAdm/DataEngineering pull request #220
Opened 2024-01-08 10:55 UTC by MarionJHolloway

# Description
Adds a new step to calculate the PA ratio from survey data. Years which did not have a survey have a PA ratio hard coded, as this is unlikely to change value in the future.

# How to test
Tests passing
Runs in branch
Compared to previous estimates and preferred

2024-01-08 14:54 UTC, garypolzin requested changes
sorry had to look through it quite quick but see what you think to the feedback below and we'll go from there

2024-01-08 14:54 UTC, garypolzin commented on utils/direct_payments_utils/estimate_direct_payments/calculate_pa_ratio.py
> +        DP.RATIO_ROLLING_AVERAGE, df[DP.SUM_OF_RATIOS] / df[DP.COUNT_OF_YEARS]
probably low priority but we are using a mix of F.col("col_name") and df["col_name"] in our code, should we try to stick to one for consistency?
Both look fairly common in our code, so we can deal with this at another point if we decide to and leave as it is now

2024-01-08 14:54 UTC, garypolzin commented on utils/direct_payments_utils/estimate_direct_payments/calculate_pa_ratio.py
> +        & (survey_df[DP.TOTAL_STAFF_RECODED] > 0.0)
assign magic numbers to a named variable to explain what they are

2024-01-08 14:54 UTC, garypolzin commented on tests/unit/test_calculate_pa_ratio.py
> +        ]
would be good to decide when test files should be in the test job and when they should be in the test file generator. Larger ones make test files quite long (but also it's easier to read answers when the test file is in the same script)

2024-01-09 09:37 UTC, MarionJHolloway commented on utils/direct_payments_utils/estimate_direct_payments/calculate_pa_ratio.py
> +        DP.RATIO_ROLLING_AVERAGE, df[DP.SUM_OF_RATIOS] / df[DP.COUNT_OF_YEARS]
I think this is a bigger issue - we might need a style guide or similar - question for MadeTech perhaps?

2024-01-09 09:37 UTC, MarionJHolloway commented on utils/direct_payments_utils/estimate_direct_payments/calculate_pa_ratio.py
> +        & (survey_df[DP.TOTAL_STAFF_RECODED] > 0.0)
Fixed!

2024-01-09 09:38 UTC, MarionJHolloway commented on tests/unit/test_calculate_pa_ratio.py
> +        ]
I've moved these out and into separate files

2024-01-09 11:27 UTC, garypolzin approved these changes
happy with emended code and decisions to defer :)

2024-01-09 11:31 UTC, merged