Define column names in one location
NMDSdevopsServiceAdm/DataEngineering pull request #232
Opened 2024-01-19 16:08 UTC by MarionJHolloway

# Description
Added column names for datasets as dataclasses in utils scripts in IND CQC pipeline
Updated column names in scripts that won't be worked on over the next ten weeks

# How to test
All unit tests passing.
As part of the commit history, I used a test script to compare changes to schemas which weren't covered by unit tests.

# Developer checklist
- [x ] Unit test
- [x ] Linked to Trello ticket
- [x ] Documentation up to date

2024-01-22 10:35 UTC, garypolzin requested changes

2024-01-22 10:35 UTC, garypolzin commented on utils/ind_cqc_column_names/estimate_jobs_columns.py
> +
I'd be tempted to merging all the column headings used in the 'CQC IND filled post estimating' process into one list of columns

The jobs are currently split up but it's one process, so a lot of the columns will be repeated. We'll need to add ICB at some point, and maybe rename job_count to filled_post_count (quite easy to do this now given we're writing prepare_locations from scratch and not editing the current one)

Looking at the miro board it looks like we'll have 5+ data files for the process of estimating CQC IND jobs, so that's a lot of repeated column names?

2024-01-22 10:35 UTC, garypolzin commented on utils/ind_cqc_column_names/ascwds_worker_columns.py
> +class AscwdsWorkerColumns:
for all the other datasets we've made the labels more readable, such as
care_home: str = "carehome"

but we've kept all the ascwds ones the same. We could just rename the ones we use for use for now then built up the list as we come to use other variables. Ideally we'd carry on the same naming conventions so 
employment_status: str = "emplstat"
main_job_role: str = "mainjrid"
etc

2024-01-22 10:35 UTC, garypolzin commented on utils/ind_cqc_column_names/ascwds_worker_columns.py
> +
This is just a random one but given all these files have somewhat changeable columns do you think we sort (and maintain them) in alphabetical order?
particularly for ascwds with 600+ columns in each file, it's easy to find 'amhp' alphabetically but less so just looking for it

2024-01-22 10:40 UTC, MarionJHolloway commented on schemas/cqc_care_directory_schema.py
> +            ColNames.ServiceType.diagnositc_sessional,
Good spot, thanks

2024-01-22 10:42 UTC, MarionJHolloway commented on utils/ind_cqc_column_names/ascwds_worker_columns.py
Direct payments column headings are quite different and can eventually be refactored into a similar folder structure. I kept this specific to this pipeline for now to avoid interdependencies later down the line

2024-01-22 10:49 UTC, MarionJHolloway commented on utils/ind_cqc_column_names/estimate_jobs_columns.py
> +
I was quite torn over which way to go with this. Maybe a compromise would be to move all the classes into one script and separate out the columns which recur in each script (e.g. location id, run dates), but keep the script specific column names in separate classes, in that same script?

2024-01-22 10:49 UTC, MarionJHolloway commented on utils/ind_cqc_column_names/ascwds_worker_columns.py
> +
Yes, good idea, I will sort them

2024-01-22 11:18 UTC, garypolzin commented on utils/ind_cqc_column_names/ascwds_worker_columns.py
merging my responses for both this comment and the 'one list per pipeline job'

I guess what I'm saying is that at this point, most of them aren't specific to this pipeline (this ASCWDS file is the version we'll use as a starting point for all ASCWDS tasks, same for CQC.

and generally conscious that we'll soon have lots of very similar datasets which will almost be identical to each other such as:
ascwds and ascwds_anon (prov and workplace)
cqc registered (for this process) and cqc_deregistered (for reconciliation)
locations_prepared, locations_prepared_cleaned, with estimates added, with job roles added

so just being wary of loads of loads of 'column_name' lists which will need maintaining, and jobs failing because we update some of them but forget one further downstream - feels better to have one list per pipeline which contains everything for the pipeline?

2024-01-22 12:35 UTC, MarionJHolloway commented on utils/ind_cqc_column_names/ascwds_worker_columns.py
If we only have one file for the whole pipeline it will be very long. Several thousand rows. With data classes you can just import the classes that are relevant to the script.

Additionally, the raw data files are a separate case. They feed the schemas and don't necessarily match the formatting of the strings in later stages of the pipeline. 

One solution could be to have the data classes feed each other (so later scripts pull in values from scripts earlier in the pipeline). For example, in prepare_locations_cleaned.py we could put something like:

import prepare_locations_column_names

location_id = prepare_locations_column_names.location_id

2024-01-22 12:49 UTC, MarionJHolloway commented on utils/ind_cqc_column_names/ascwds_worker_columns.py
> +class AscwdsWorkerColumns:
Yeah, I agree - it's about 1500 variables to rename, so we could put in the time up front or just clean them up as we use them. I'm happy either way :)

2024-01-22 12:52 UTC, garypolzin commented on utils/ind_cqc_column_names/ascwds_worker_columns.py
It wouldn't be that long, the full ASCWDS files aren't part of the pipeline. The pipeline for estimating jobs starts with the merging process, so at the moment it would be a combination of the
44 col names in prepare_locations
22 col names in prepare_locations_cleaned (however I think all but one col_name is in prepare_locations)
23 col names in estimate_jobs (I think only 7 are 'new' columns

so these 3 column lists with 89 column names could be reduced to one list of 52 names - the initial list in prepare_locations plus the additional 1 in prepare_locations_cleaned and 7 in estimate_jobs

2024-01-23 08:23 UTC, garypolzin approved these changes

2024-01-23 08:57 UTC, merged