Setup script merge ind cqc filled posts
NMDSdevopsServiceAdm/DataEngineering pull request #261
Opened 2024-02-13 17:45 UTC by MarionJHolloway

# Description
Setup script and glue job for merge_ind_cqc_data.py

https://trello.com/c/lS60F5Ak/11-epic-7-set-up-script-and-glue-job-merge-ind-cqc-filled-posts-data-must 

# How to test
Unit tests passing
Runs successfully in branch

# Developer checklist
- [x] Unit test
- [x] Linked to Trello ticket
- [ ] Documentation up to date

2024-02-13 17:47 UTC, MarionJHolloway commented on terraform/pipeline/glue.tf
> +    "--cleaned_ascwds_workplace_source" = "${module.datasets_bucket.bucket_uri}/domain=ASCWDS/dataset=workplace_cleaned/"
As I was making this I noticed that some of our datasets in s3 use underscores instead of hyphens. We might want to create a ticket to fix this, as it got quite confusing working out which was which when testing in branch, copying over datasets to test etc.

2024-02-14 09:20 UTC, james-francis-MT commented on terraform/pipeline/glue.tf
> +    "--cleaned_ascwds_workplace_source" = "${module.datasets_bucket.bucket_uri}/domain=ASCWDS/dataset=workplace_cleaned/"
Yeah, I think it is worth doing this sooner rather than later. Would be good to get at least all of the formatting post cleaning aligned

2024-02-14 10:59 UTC, james-francis-MT approved these changes
Nice one

2024-02-15 09:01 UTC, garypolzin requested changes

2024-02-15 09:01 UTC, garypolzin commented on jobs/merge_ind_cqc_data.py
> +        append=True,
Happy to approve if that's not correct though

2024-02-15 09:57 UTC, luke-a-williams commented on terraform/pipeline/glue.tf
> +    "--cleaned_ascwds_workplace_source" = "${module.datasets_bucket.bucket_uri}/domain=ASCWDS/dataset=workplace_cleaned/"
Definitely, can we get an idea of how many have underscores names there are and get a ticket together?

2024-02-15 10:11 UTC, MarionJHolloway commented on jobs/merge_ind_cqc_data.py
> +        append=True,
We can do this, but it should be a separate ticket. We will need to refactor the write_to_parquet functions in utils to include an option for overwrite mode that we can then select for these jobs. This will also affects our choices on run dates , partitioning, versioning etc.

2024-02-15 10:14 UTC, MarionJHolloway commented on terraform/pipeline/glue.tf
> +    "--cleaned_ascwds_workplace_source" = "${module.datasets_bucket.bucket_uri}/domain=ASCWDS/dataset=workplace_cleaned/"
It seems like there are more underscores than hyphens in our glue modules file! I think we need to decide which way to go and make it consistent. I will write a ticket.

2024-02-15 10:14 UTC, luke-a-williams requested changes
Quick review on top of others spotted an error?

2024-02-15 10:14 UTC, luke-a-williams commented on terraform/pipeline/glue.tf
> +    "--ons_postcode_directory_source"   = "${module.datasets_bucket.bucket_uri}/domain=ONS/dataset=postcode-directory//"
Is this directory location correct? Should it be `"${module.datasets_bucket.bucket_uri}/domain=ONS/dataset=postcode-directory/"`

2024-02-15 10:18 UTC, garypolzin commented on jobs/merge_ind_cqc_data.py
> +        append=True,
ah ok - in the short term is it better to amend or not to append?!
I guess it doesn't matter as we need to delete and re-run for it to be useable anyway

2024-02-15 10:21 UTC, MarionJHolloway commented on jobs/merge_ind_cqc_data.py
> +        append=True,
I can set it to not append if you prefer. We can prioritise the ticket that allows an overwrite option so it is done before we start running this job properly

2024-02-15 10:22 UTC, garypolzin commented on jobs/merge_ind_cqc_data.py
> +        append=True,
I guess append is redundant once overwrite is an option so just leave as it is

2024-02-15 10:23 UTC, garypolzin approved these changes

2024-02-15 10:54 UTC, luke-a-williams approved these changes
GTM

2024-02-15 12:00 UTC, merged