Purge outdated workplace data
NMDSdevopsServiceAdm/DataEngineering pull request #265
Opened 2024-02-15 10:31 UTC by james-francis-MT

# Description
Purge outdated ascwds workplace data

# How to test
Currently testing in branch but though I would raise this PR so people could take a look

# Developer checklist
- [ ] Unit test
- [ ] Linked to Trello ticket
- [ ] Documentation up to date

2024-02-15 11:55 UTC, james-francis-MT commented on jobs/clean_ascwds_workplace_data.py
> -        ascwds_workplace_df, PartitionKeys.import_date, AWPClean.import_date
The wrong string was being used here so corrected

2024-02-15 11:55 UTC, james-francis-MT commented on jobs/clean_ascwds_workplace_data.py
> +def purge_outdated_workplaces(df: DataFrame, comparison_date_col: str) -> DataFrame:
Not sure how to make this any more readable - suggestions welcome

2024-02-15 12:02 UTC, MarionJHolloway requested changes

2024-02-15 12:02 UTC, MarionJHolloway commented on jobs/clean_ascwds_workplace_data.py
> +def purge_outdated_workplaces(df: DataFrame, comparison_date_col: str) -> DataFrame:
You could abstract some of these steps into small functions so you can describe what they're doing?

2024-02-15 12:07 UTC, james-francis-MT commented on jobs/clean_ascwds_workplace_data.py
> +        ascwds_workplace_df, "ascwds_workplace_import_date"
Ahh yes, I forgot to change after merging main - nice spot

2024-02-15 12:09 UTC, james-francis-MT commented on jobs/clean_ascwds_workplace_data.py
> +def purge_outdated_workplaces(df: DataFrame, comparison_date_col: str) -> DataFrame:
Yeah I can try that but they will be very specific to this function - I guess that's okay though

2024-02-15 12:10 UTC, MarionJHolloway commented on jobs/clean_ascwds_workplace_data.py
> +def purge_outdated_workplaces(df: DataFrame, comparison_date_col: str) -> DataFrame:
Yeah, I think that's fine, if it makes it clearer what it's doing

2024-02-15 12:22 UTC, james-francis-MT commented
@MarionJHolloway What do you think of the test structure? This allows you to run individual tests for a function but still keep the general setUp stuff

2024-02-15 14:21 UTC, james-francis-MT commented on jobs/clean_ascwds_workplace_data.py
> +def purge_outdated_workplaces(df: DataFrame, comparison_date_col: str) -> DataFrame:
I've extracted out some of the functionality - hope that makes it a bit more readable

2024-02-15 14:37 UTC, garypolzin requested changes

2024-02-15 14:37 UTC, garypolzin commented on jobs/clean_ascwds_workplace_data.py
> +    )
please can you change so that
if F.col("latest_update") < F.col("purge_date") is True then "Purge"
otherwise "keep"

easier than having to check/remember if True means that the data is good or if True means delete them!

2024-02-15 15:35 UTC, james-francis-MT commented on jobs/clean_ascwds_workplace_data.py
> +    )
Sure, in my head if( purge_data ){ purge_data() } made sense but happy either way

2024-02-15 15:40 UTC, garypolzin commented on jobs/clean_ascwds_workplace_data.py
> +    )
yea, there's another purge which we do (but isn't part of this project) so we'll have 2 purge columns

it definitely does make sense, but I just know I'll keep looking at it thinking is it right that I'm seeing the True's or should they be ones which we need to be removed

keep=keep and purge=delete is better for my tired brain!

2024-02-15 17:23 UTC, MarionJHolloway approved these changes
Looks good to me

2024-02-16 10:36 UTC, garypolzin approved these changes
looks great thanks!

2024-02-16 10:36 UTC, merged