Remove rows where loc id is duplicated
NMDSdevopsServiceAdm/DataEngineering pull request #285
Opened 2024-02-22 16:15 UTC by james-francis-MT

# Description
remove locations where location id is duplicated for the same import date

# How to test
Currently testing in branch

https://trello.com/c/9to9YH3t/183-epic-5-remove-all-rows-where-the-locationid-is-duplicated-in-ascwds-workplace-file-must

# Developer checklist
- [ ] Unit test
- [ ] Linked to Trello ticket
- [ ] Documentation up to date

2024-02-22 16:28 UTC, garypolzin requested changes
the function looks alright but it needs adding to the clean_ascwds_workplace_data script please, not this one :)

2024-02-22 17:53 UTC, luke-a-williams commented on jobs/clean_ascwds_workplace_data.py
> +    df_without_duplicates = df_with_count.filter(F.col("location_id_count") == 1)
Your tests explain what you are trying to achieve here very well.

2024-02-22 17:54 UTC, luke-a-williams approved these changes
GTM

2024-02-23 10:16 UTC, james-francis-MT commented on tests/unit/test_clean_cqc_location_data.py
>  import warnings
Just splitting them up so you can run each set of tests for each function

2024-02-23 13:18 UTC, merged