Dedup ascwds scale variables
NMDSdevopsServiceAdm/DataEngineering pull request #286
Opened 2024-02-22 16:31 UTC by garypolzin

# Description
This function creates a new column and only transfers 'newly submitted' values across. If the data is repeated from the previous submission then it changed to a null value

I haven't run this in branch yet but opening PR so you can comment on the code in the meantime

[Trello](https://trello.com/c/oTQjSVbj/115-epic-5-create-de-duplication-script-blocked-awaiting-james-show-and-tell-must)

# Developer checklist
- [X] Unit test
- [X] Linked to Trello ticket
- [X] Documentation up to date

2024-02-22 17:56 UTC, luke-a-williams commented on jobs/clean_ascwds_workplace_data.py
> +    """
Nice docstring!

2024-02-22 18:53 UTC, luke-a-williams requested changes
Single missed test case line, happy to approve after a discussion or change on this.

2024-02-23 08:27 UTC, garypolzin commented on tests/unit/test_clean_ascwds_workplace_data.py
> +        )
I've got a full data frame comparison test at the end so just randomly picked 2 cases for this specific check, so the other case is captured, just not here.

I'm happy to add if you see fit, but if that one case were to be wrong it would cause another test to fail

2024-02-23 11:06 UTC, luke-a-williams commented on tests/unit/test_clean_ascwds_workplace_data.py
> +        )
That's true, technically captured by the full data test

2024-02-23 11:06 UTC, luke-a-williams approved these changes
Discussed test with Gary, GTM provided it passes integration tests

2024-02-23 16:04 UTC, merged