Remove duplicate entries carehome pir
NMDSdevopsServiceAdm/DataEngineering pull request #287
Opened 2024-02-22 17:36 UTC by luke-a-williams

# Description
Introduced the logic required for ticket https://trello.com/c/WgXg2dlh/191-epic-2-remove-duplicates-from-pir-data-must
Split into two parts:
- The new utils function `latest_datefield_for_grouping` which in the specific case of multiple submission dates existing for a pir import date still returns duplicates, but grouped to the required grouping
- an additional drop duplicates function call after to remove said duplicate same submission id, to only return one submission id per grouping.

I also refactored some other tests in the region to be more to purpose and requiring less return value patching.

# How to test
I created a notebook demonstrating this functionality on the larger dataset as I needed to be careful with exactly how the duplicates were being dropped after filtering. If you need to, you can spin up the notebook [here](https://e-df1p29ja8qe2vrn13q5ydsmzg.emrnotebooks-prod.eu-west-2.amazonaws.com/workspace/doc/tree/pir_clean_dedupe.ipynb) or otherwise find it within my notebooks under `pir_clean_dedupe`

I've designed the function and placed it in utils so that the grouping and filtering to return the latest of a target column can be re-used elsewhere, although I'm happy to isolate it to the clean_cqc_pir area if required

# Developer checklist
- [ ] Unit test
- [ ] Linked to Trello ticket
- [ ] Documentation up to date

2024-02-23 09:54 UTC, luke-a-williams commented on utils/utils.py
> +    df: DataFrame, grouping_column_list: list[Column], date_field_column: Column
This type was not sub-scriptable in the test run, so changing

2024-02-23 14:12 UTC, garypolzin requested changes

2024-02-23 14:12 UTC, garypolzin commented on tests/test_file_data.py
> +    ]
might be good to add a duplicate row but change the careHome value from "Y" to "N" to check that isn't removed

Also to replicate raw data the 3rd column should be in the format "20220201" and the final column is the same date but as an actual date --> date(2022, 2, 1)

2024-02-23 14:12 UTC, garypolzin commented on tests/unit/test_utils.py
> +        self.assertEqual(after_df.count(), 4)
Can I just double check the functionality - is this 4 rows at this point as the exact duplicate row keeps both records (as both are most recent)

then the other function removes one of these (rank=1) so that the final dataset correctly has 3 rows

2024-02-23 16:34 UTC, luke-a-williams commented on tests/unit/test_utils.py
> +        self.assertEqual(after_df.count(), 4)
To answer your question with that knowledge, it is 4 rows because the duplicate submission date isn't eliminated at this point, and the test case was picked deliberately to show this. We could argue we need a test case to show that submission date appears twice, to be fair.

2024-02-23 16:35 UTC, luke-a-williams commented on tests/test_file_data.py
> +    ]
We should probably discuss this if I'm changing data types as a lot of the logic was built around the original column being a string, and needing to be converted to a date.

2024-02-26 08:32 UTC, garypolzin commented on tests/unit/test_utils.py
> +        self.assertEqual(after_df.count(), 4)
Yea that's what I thought thanks, just wanted to double check!

2024-02-26 09:00 UTC, garypolzin commented on tests/test_file_data.py
> +    ]
yes that's correct, they are strings initially but the functions in main on row 21 and 24 convert the original strings to dates

Your function starts after these two functions on row 33 so at that point the two columns are dates, not strings

2024-02-26 13:44 UTC, garypolzin approved these changes

2024-02-26 14:25 UTC, merged