Apply job role labels to workers
NMDSdevopsServiceAdm/DataEngineering pull request #295
Opened 2024-02-27 17:35 UTC by MarionJHolloway

# Description
https://trello.com/c/AGBViNOT/48-epic-6-apply-labels-to-ascwds-worker-file-for-mainjrid-job-roles-must

To complete this ticket we had to 

*Change the function that applies the labels to the dataframe
*Limit the datasets to only the relevant columns
*Update tests and test data
*Change the structure of the labels in utils

# How to test
Unit tests passing
Runs successfully in branch on full dataset

# Developer checklist
- [x] Unit test
- [x] Linked to Trello ticket

2024-02-28 11:36 UTC, luke-a-williams requested changes
Couple of terraform and print statement changes

2024-02-28 11:36 UTC, luke-a-williams commented on terraform/pipeline/glue.tf
> +  number_of_workers = 6
Do we need this level of power now? Can it be reduced?

2024-02-28 11:36 UTC, luke-a-williams commented on utils/cleaning_utils.py
> +        print(column_name)
Can these be removed?

2024-02-28 11:36 UTC, luke-a-williams commented on utils/cleaning_utils.py
> +            df.show()
can shows and prints be removed?

2024-02-28 11:36 UTC, luke-a-williams commented on utils/utils.py
> +    data_source: str, selected_columns: list = None
Why are we changing this back? Has something changed which breaks this?

2024-02-28 11:36 UTC, luke-a-williams commented on utils/value_labels/ascwds_worker/worker_label_dictionary.py
> +    AscwdsWorkerValueLabelsMainjrid.column_name: AscwdsWorkerValueLabelsMainjrid.labels_dict
OK I see what you've done here, making it a dictionary with a nested dictionary you can call later, nice!

2024-02-28 14:56 UTC, luke-a-williams commented on utils/utils.py
> +    data_source: str, selected_columns: list = None
James discovered that in python 3.7, the version glue uses, this doesn't work. Whilst in python 3.9, the version our project is written in, this does work. This is why it looks ok locally but falls over in Glue jobs

2024-02-29 10:41 UTC, james-francis-MT approved these changes

2024-02-29 11:22 UTC, MarionJHolloway commented on tests/unit/test_cleaning_utils.py
Yes the ones removed were for functions no longer needed and didn't cover testing of functions that remain

2024-02-29 11:37 UTC, MarionJHolloway commented on tests/unit/test_cleaning_utils.py
> -
Yes, have removed these now - good spot!

2024-02-29 11:39 UTC, MarionJHolloway commented on tests/unit/test_cleaning_utils.py
> -
Labels schema has gone and data.gender is needed elsewhere

2024-02-29 11:42 UTC, MarionJHolloway commented on utils/utils.py
> +    data_source: str, selected_columns: list = None
As Luke said, it works in CircleCI but it breaks in Glue. When I ran this job in branch to test before the PR, this was the step that was causing it to crash, so I fixed it.

2024-02-29 11:48 UTC, MarionJHolloway commented on utils/utils.py
> +    data_source: str, selected_columns: list = None
https://eu-west-2.console.aws.amazon.com/gluestudio/home?region=eu-west-2#/job/apply-job-role-labels-to-worke-clean_ascwds_worker_data_job/run/jr_cfe75c387ab810b6f811c5b0498a5f888a74b07afe85cdf74ad7e7d1a97e53f4

This is the run that shows the error

2024-02-29 11:55 UTC, garypolzin commented on utils/utils.py
> +    data_source: str, selected_columns: list = None
yea it was broken on the 27th when you ran that job so we changed it yesterday - hence if you pull from main it will change to 'List[str]' (capital L works, lower case l doesn't)

but it doesn't need changing again to 'list'

2024-02-29 11:57 UTC, MarionJHolloway commented on utils/utils.py
> +    data_source: str, selected_columns: list = None
Ah I see, sorry, didn't spot the capitalisation! I will add back in

2024-02-29 12:01 UTC, garypolzin commented on utils/utils.py
> +    data_source: str, selected_columns: list = None
no worries, this caused a lot of confusion yesterday!

came across another function yesterday too which works fine in our python 3.9.6 but doesn't in Glues python 3.7, might be something to think about

2024-02-29 12:09 UTC, garypolzin commented on jobs/clean_ascwds_worker_data.py
> +]
sorry I was meaning to move out of this script and into the same place as the column names/values - it's a short list now but will end up being 30+ long when we get round to bringing in gender etc

utils > column_names > cleaned_data_files > ascwds_worker_cleaned_values

so there would be 3 classes in there
- column names
- values
- column list for import

2024-02-29 12:14 UTC, MarionJHolloway commented on jobs/clean_ascwds_worker_data.py
> +]
Isn't the list of columns quite specific to this script? We may want different columns from the same files in different scripts depending on what get joined where?

2024-02-29 12:15 UTC, james-francis-MT commented on jobs/clean_ascwds_worker_data.py
> +]
I said the same thing in my PR 😆

2024-02-29 12:20 UTC, garypolzin commented on jobs/clean_ascwds_worker_data.py
> +]
yea it is, but I also thought that the file above was also specific to this file?

if we filter want to import a subset of the worker file in our ind_cqc_pipeline then we'd put the column list to import into
utils > column_names > ind_cqc_pipeline_columns

2024-02-29 12:30 UTC, garypolzin commented on jobs/clean_ascwds_worker_data.py
> +]
at the moment every job has a column name file, so I just assumed that it was 1-1 and the import list for that job could go in the list

either way, this cleaned ASCWDS job will end up having at least 30+ columns imported so it would be good to have something in place now to account for that list getting long

2024-02-29 12:31 UTC, MarionJHolloway commented on jobs/clean_ascwds_worker_data.py
> +]
No, the column names are specific to the dataset, not the job. This job also import the column names for the workplace file, for example, because that file is loaded here too. I'll push through what the changes would look like.

Generally, good reasons to abstract code are to prevent repetition (i.e. it's used in many places, write it once and reference it many times, like the column names) for unit testing functions in logical blocks. 

We also don't have a plan for what we are doing with the worker data yet and keeping the short list of selected columns in the job is less commiting than abstracting it. We might end up having multiple cleaned worker files, each with a subset of data, so we don't have to rerun everything in the pipeline, who knows.

2024-02-29 12:39 UTC, MarionJHolloway commented on jobs/clean_ascwds_worker_data.py
> +]
I also feel like this is a bigger decision about how we structure our code than is within the scope of this ticket. It will impact a lot of code that isn't within scope here. This ticket was about getting the labels on the worker file, selecting the columns was only necessary to stop the glue job falling over. I've certainly not considered the implications for abstracting this in all the scripts.

2024-02-29 12:46 UTC, MarionJHolloway commented on jobs/clean_ascwds_worker_data.py
> +]
I've pushed through something like what you suggested

2024-02-29 12:53 UTC, garypolzin commented on jobs/clean_ascwds_worker_data.py
> +]
yea that's what I was thinking

The end goal should be one 'clean' ascwds file - so that file can contain all the columns we pull into it plus the names of them all and any values
We'll have the other files which will contain all the categorical label names etc

then all other pipelines use this clean version as the starting point. but they'll have their own column_name file (like ind_cqc_pipeline_columns does, and that can contain the column import list for that pipeline

2024-02-29 13:14 UTC, garypolzin approved these changes
Pretty sure all my comments have been addressed so I'll approve now, thanks!

2024-02-29 13:49 UTC, luke-a-williams requested changes
minor thing

2024-02-29 13:49 UTC, luke-a-williams commented on terraform/pipeline/glue.tf
> +  number_of_workers = 3
Did you want to keep this as 3? Or change it back to the default of 2?

2024-02-29 15:07 UTC, luke-a-williams commented on jobs/clean_ascwds_worker_data.py
> +]
I think the column names directory should be kept to just that - column names defined by a dataclass for a dataset.
For me, there are 3 main ideologies which I think are relevant here:

- Having a central point of truth for schema definition, otherwise known as standardising column names, at a point during or before the bronze data layer.
- Aiming for minimal code entanglement.
- Keeping code clean and maintainable.

The original column names, i.e. ascwds_worker_column names, define the original schema in the bronze layer, and this class is extended for the cleaned column names, as it's an extension of the original dataset columns. As a general rule of thumb, it should always be inherited from there, and it ensures that location is the central point of truth for those column definitions. **They should be associated with that dataset, NOT the job.**
If you start defining columns per job in an abstract script, it risks over abstraction and reduced clarity and readability of the code, as well as risks eroding the data dictionary you have per dataset.

As for code cleanliness and maintainability, if you start defining workplace variables in worker column name files, and vice versa, you create a need to keep repeating this everytime, creating all of these new lists that are specific to each select statement. As you increase the number of cleaning jobs, and selecting subsets of data, that file starts to grow unmanageable, and it's likely you will miss exact definitions that suit your purpose that have already been created, increasing risk of duplicating code. I think in this case it is an over-abstraction, when actually it is perfectly viable and cleaner to define the selected columns **within the script they are being select**. This also increases readability in glue, where your view is isolated to the job itself.

Hopefully that makes some degree of sense.

2024-02-29 15:15 UTC, garypolzin commented on jobs/clean_ascwds_worker_data.py
> +]
Yea fair enough

was just thinking about those files with 800 columns, and we might want to import 50 of them. The script then starts with 50 rows of all the columns to import, and then we're frequently merging in one/two/three other datasets too, so could easily end up with 100+rows of all the columns to import into that job.

So let's not do this approach, but I think we need an approach

2024-02-29 15:52 UTC, luke-a-williams commented on jobs/clean_ascwds_worker_data.py
> +]
Lets have a chat Gary, because your points are completely valid and I want to make sure we are on the same page and find a good solution

2024-02-29 15:53 UTC, luke-a-williams approved these changes

2024-02-29 17:21 UTC, merged