Clean ons data job
NMDSdevopsServiceAdm/DataEngineering pull request #309
Opened 2024-03-05 14:20 UTC by garypolzin

# Description
We were having issues with multiple postcode joins in one script so created a cleaning script which reformats the geography data to contain a lot less columns and only requires one join now to bring in all geography data, past and present.

All columns are still accessible too, in case we need them further down the pipeline

This will also make the unmatched postcodes easier to identify as there is only one join

Haven't tested in branch yet but the PR is a bit of a beast so opening the PR now

[Trello](https://trello.com/c/e6DLgcpH/293-epic-4-create-clean-ons-job-and-refactor-columns-must)

# Developer checklist
- [X] Unit test
- [X] Linked to Trello ticket
- [X] Documentation up to date

2024-03-05 14:45 UTC, garypolzin commented on jobs/clean_ons_data.py
> +        ONSClean.ons_import_date,
this function is called twice, once for contemporary and once for current so it needs to be `ons_import_date`

2024-03-05 14:46 UTC, garypolzin commented on jobs/clean_ons_data.py
> +        ONSClean.ons_import_date,
the alias is where we assign current vs contemporary

2024-03-05 14:49 UTC, MarionJHolloway commented on tests/unit/test_clean_ons_data.py
> +        self.assertEqual(
It looks like this is only testing one row of data, when it needs to check that none of the rows contain a different date

2024-03-05 14:52 UTC, MarionJHolloway commented on jobs/clean_ons_data.py
> +        ONSClean.ons_import_date,
In row 52 you rename the import date for the current data. I'm suggest that instead of having two date columns in the final dataframe called ons_import_date and current_ons_import_date, we have columns called contemporary_ons_import_date and current_ons_import_date to avoid confusion. You could do it as the last step in the job if that makes more sense.

2024-03-05 14:53 UTC, MarionJHolloway commented on jobs/clean_ons_data.py
> +    refactored_ons_with_current_ons_df = refactored_ons_df.join(
This join is untested, worth refactoring into a function so you can test it?

2024-03-05 14:55 UTC, MarionJHolloway commented on tests/unit/test_clean_ons_data.py
> +class PrepareCurrentONSTests(CleanONSDatasetTests):
This class had two tests in the locations script, are they not both needed now for some reason?

2024-03-05 14:55 UTC, garypolzin commented on jobs/clean_cqc_location_data.py
> +def join_ons_postcode_data_into_cqc_df(
possibly yes - it's hard to read in this format but we previously had 2 postcode join functions

`join_current_ons_postcode_data` - I deleted this

`join_contemporary_ons_postcode_data` - I pretty much removed the word contemporary and this became the new function. Then also added in the two postcode related tasks from main so all geography tasks contained in one function

So I can put it all into main but the same joins weren't in main before, I don't know the benefits/downsides of either approach so happy either way

2024-03-05 14:57 UTC, MarionJHolloway commented on utils/column_names/cleaned_data_files/cqc_location_cleaned_values.py
> -    current_cssr: str = "current_" + ONS.cssr
These removed column names are used in later scripts and will want refactoring in everything downstream as well

2024-03-05 15:05 UTC, MarionJHolloway commented on jobs/clean_cqc_location_data.py
> +def join_ons_postcode_data_into_cqc_df(
The join function seems to be within this join function?

2024-03-05 15:06 UTC, garypolzin commented on jobs/clean_ons_data.py
> +        ONSClean.ons_import_date,
ah got you, I've done this

2024-03-05 15:48 UTC, garypolzin commented on jobs/clean_cqc_location_data.py
> +def join_ons_postcode_data_into_cqc_df(
all in one function now :)

2024-03-05 15:52 UTC, garypolzin commented on tests/unit/test_clean_ons_data.py
> +        self.assertEqual(
yea wasn't sure how specific to go with tests

original df has 5 rows in - 3 have the latest date and the other 2 have older dates

so I checked the returned file has 3 rows in and that the date for one of them was the most recent date as a double check - I can add the other rows as checks too

2024-03-05 15:55 UTC, garypolzin commented on utils/column_names/cleaned_data_files/cqc_location_cleaned_values.py
> -    current_cssr: str = "current_" + ONS.cssr
thought I'd leave some work for another ticket!

2024-03-05 16:01 UTC, garypolzin commented on tests/unit/test_clean_ons_data.py
> +class PrepareCurrentONSTests(CleanONSDatasetTests):
yea the other was checking that columns had been renamed correctly but we aren't doing that step anymore

2024-03-05 16:20 UTC, garypolzin commented on tests/unit/test_clean_ons_data.py
> +        self.assertEqual(
done :)

2024-03-05 16:51 UTC, MarionJHolloway commented on utils/column_names/cleaned_data_files/cqc_location_cleaned_values.py
> -    current_cssr: str = "current_" + ONS.cssr
We will need to bring that ticket into this sprint. I've added it to the top of sprint 4 so it doesn't get lost in new tickets

2024-03-05 16:53 UTC, MarionJHolloway reviewed
Looks good to me, it would be good to get another set of eyes on this though, as it's a big PR, so haven't approved. Also haven't requested changes through the review process because I'm off tomorrow and don't want to block it merging.

2024-03-05 17:09 UTC, luke-a-williams reviewed
Initial comments on a quick scan of the code

2024-03-05 17:09 UTC, luke-a-williams commented on jobs/clean_cqc_location_data.py
>      cqc_location_df = remove_non_social_care_locations(cqc_location_df)
Can this logic be moved to line 63 since it is a where clause and would effectively reduce the amount of data the rest of the transformations would need to be performed on? I can have a look in Glue and see how much of a difference this might make if you aren't certain about moving it..

2024-03-05 17:09 UTC, luke-a-williams commented on jobs/clean_cqc_location_data.py
>      cqc_location_df = add_list_of_services_offered(cqc_location_df)
This function and allocate_primary_service_type could be faster when ran before the joins, as it would be working on less data... unless it requires dependence on joined columns.
If there is dependence on joined columns, then the order of these functions matters and should be tested

2024-03-05 17:12 UTC, luke-a-williams commented on jobs/clean_ons_data.py
> +    ons_df = utils.read_from_parquet(ons_source)
Is it necessary to read in ALL of the ons columns - or can a core subset be selected to significantly improve run-times?

2024-03-05 17:16 UTC, luke-a-williams commented on jobs/clean_ons_data.py
> +    )
Since this function's purpose seems to perform a select operation on the ONS data, can this logic be moved to follow immediately after the read operation for optimisation purposes?

2024-03-06 08:28 UTC, garypolzin commented on utils/column_names/cleaned_data_files/cqc_location_cleaned_values.py
> -    current_cssr: str = "current_" + ONS.cssr
just checked and we don't actually pull any geography columns into the merge script yet so even if these column names were added now it wouldn't run downstream as the columns don't exist yet. I've create a ticket

2024-03-06 08:38 UTC, garypolzin commented on jobs/clean_cqc_location_data.py
>      cqc_location_df = add_list_of_services_offered(cqc_location_df)
I've reordered all the functions so all the location stuff happens first, then the two joins at the end of the job

2024-03-06 08:57 UTC, garypolzin commented on jobs/clean_ons_data.py
> +    ons_df = utils.read_from_parquet(ons_source)
I've refactored the ONS data so it now looks like below.

![image](https://github.com/NMDSdevopsServiceAdm/DataEngineering/assets/94380092/3bb192a5-3392-4ed5-97a1-649a54891e6f)

The schema is:
 |-- HYBRID_POSTCODE: string (nullable = true)
 |-- contemporary_ons_import_date: date (nullable = true)
 |-- contemporary: struct (nullable = false)
 |    |-- CSSR: string (nullable = true)
 |    |-- Region: string (nullable = true)
 |    |-- Sub_ICB: string (nullable = true)
 |    |-- ICB: string (nullable = true)
 |    |-- ICB_Region: string (nullable = true)
 |    |-- CCG: string (nullable = true)
 |    |-- lat: string (nullable = true)
 |    |-- long: string (nullable = true)
 |    |-- imd: string (nullable = true)
 |    |-- lsoa11: string (nullable = true)
 |    |-- msoa11: string (nullable = true)
 |    |-- ru11ind: string (nullable = true)
 |    |-- lsoa21: string (nullable = true)
 |    |-- msoa21: string (nullable = true)
 |    |-- pcon: string (nullable = true)
 |-- year: string (nullable = true)
 |-- month: string (nullable = true)
 |-- day: string (nullable = true)
 |-- import_date: string (nullable = true)
 |-- current_ons_import_date: date (nullable = true)
 |-- current: struct (nullable = true)
 |    |-- CSSR: string (nullable = true)
 |    |-- Region: string (nullable = true)
 |    |-- Sub_ICB: string (nullable = true)
 |    |-- ICB: string (nullable = true)
 |    |-- ICB_Region: string (nullable = true)
 |    |-- CCG: string (nullable = true)
 |    |-- lat: string (nullable = true)
 |    |-- long: string (nullable = true)
 |    |-- imd: string (nullable = true)
 |    |-- lsoa11: string (nullable = true)
 |    |-- msoa11: string (nullable = true)
 |    |-- ru11ind: string (nullable = true)
 |    |-- lsoa21: string (nullable = true)
 |    |-- msoa21: string (nullable = true)
 |    |-- pcon: string (nullable = true)

2024-03-06 09:08 UTC, garypolzin commented on jobs/clean_ons_data.py
> +    )
it is a select function but it doesn't drop any columns, it's the approach I've taken to refactor the df

we start with a df containing 21 columns
we finish with a df containing 7 column - all 15 geog columns are combined into one column which we can extract later

we can access the actual geogs we need later on by including the following
    df = df.withColumn(
        "current_cssr", df[ONSClean.current].cssr
    )

2024-03-06 10:53 UTC, james-francis-MT reviewed
Would like to see this tested in branch fully to check it doesn't impact later jobs but otherwise looks good

2024-03-06 10:53 UTC, james-francis-MT commented on jobs/clean_ons_data.py
> +    # Python logic ---> all in main
Probably no need for these comments

2024-03-06 10:53 UTC, james-francis-MT commented on jobs/clean_ons_data.py
> +    )
What is the reason for squashing columns like this if you need to extract them later anyway?

2024-03-06 11:55 UTC, luke-a-williams commented
@james-francis-MT I've been running it through with Gary, didn't make a lot of comments on the PR as tests were failing and we got the tests working just now, so going to re-review

2024-03-06 11:57 UTC, luke-a-williams commented on jobs/clean_ons_data.py
> +    ons_df = utils.read_from_parquet(ons_source)
@james-francis-MT ^^ this image might help answer your other question as to why it is being squashed, it's being run twice and its a lot of columns that currently aren't being used but don't want to be lost... or so I understand.

2024-03-06 12:07 UTC, luke-a-williams requested changes

2024-03-06 12:07 UTC, luke-a-williams commented on jobs/clean_ons_data.py
> +def prepare_current_ons_data(df: DataFrame) -> DataFrame:
Can we get a docstring in here describing how this function is used and what it is doing?
My understanding is that you pass it a complete ons dataframe and it goes and finds the latest import date for each geography with the various fields of that geography, returning the df without partition keys

2024-03-06 12:07 UTC, luke-a-williams commented on jobs/clean_ons_data.py
> +    )
Optimisation I think, looking at the job it's running in 3 minutes even with a join being present which is pretty good. But the probable answer is "this is what was being done before"... Gary might be able to shine some more light on this.

2024-03-06 12:07 UTC, luke-a-williams commented on jobs/clean_ons_data.py
> +    # Where we tell Glue how to run the file, and what to print out
Don't need this comment

2024-03-06 12:07 UTC, luke-a-williams commented on jobs/clean_ons_data.py
> +) -> DataFrame:
Can we get a docstring for this function? The order of the supplied dfs is important as it will still not error if they are put in the wrong way, so an explanation in the parameters of the docstring will help with this. If they are put in the wrong way, as we discussed, you'll just have a lot of empty rows where a newer geography doesn't have an older record.

2024-03-06 12:11 UTC, garypolzin commented on jobs/clean_ons_data.py
> +    ons_df = utils.read_from_parquet(ons_source)
yea geographies are a bit different to other cols. We probably won't use many geographies during the pipeline but we might want access to some/all of them at the end when splitting our estimated outputs out. There are 30 geog columns (15 contemporary, 15 current) so this reduces them into 2 cols whilst still being able to access them all at any point

this wasn't really the main objective of the ticket though. We were previously cleaning ONS data in the CQC locations job and having to do 2 joins - this new file means that we only need one join in CQC locations job

2024-03-06 12:12 UTC, luke-a-williams requested changes
Mismatch in job parameters also causing failures in glue pipeline

2024-03-06 12:12 UTC, luke-a-williams commented on terraform/pipeline/glue.tf
> +    "--ons_postcode_directory_source"    = "${module.datasets_bucket.bucket_uri}/domain=ONS/dataset=postcode_directory_cleaned/"
should we call this cleaned_ons_postcode_directory_source? So as not to cause confusion with the postcode directory source in other scripts.

2024-03-06 12:12 UTC, luke-a-williams commented on jobs/clean_cqc_location_data.py
> +            "--cleaned_ons_postcode_directory_source",
Relating to my other comment, since it is called cleaned_ons_postcode_directory_source here it won't work in your current terraform definitions

2024-03-06 12:14 UTC, garypolzin commented on jobs/clean_ons_data.py
> +    )
yea just makes for a smaller file for joining - 9 columns instead of 27

2024-03-06 12:15 UTC, garypolzin commented on jobs/clean_ons_data.py
> +    # Python logic ---> all in main
yea I'll remove them - I copied clean_cqc_provider_data to get started so they've come from there

2024-03-06 12:20 UTC, garypolzin commented on terraform/pipeline/glue.tf
> +    "--ons_postcode_directory_source"    = "${module.datasets_bucket.bucket_uri}/domain=ONS/dataset=postcode_directory_cleaned/"
good spot, I'd missed this one

2024-03-06 12:25 UTC, garypolzin commented on jobs/clean_ons_data.py
> +def prepare_current_ons_data(df: DataFrame) -> DataFrame:
yep that's right, for each postcode throughout time it will add what the current set of geographies are now

need to drop the partition keys as these relate to the current data only, the partition keys we want to keep are already in the main df

2024-03-06 12:29 UTC, garypolzin commented
> Would like to see this tested in branch fully to check it doesn't impact later jobs but otherwise looks good

Will test this in branch but geographies aren't pulled into merge_ind_cqc yet, there's a separate ticket to include them
https://trello.com/c/kNSG2IRc/295-epic-7-bring-geographies-into-mergeindcqcdata-job-must

2024-03-06 12:36 UTC, luke-a-williams requested changes

2024-03-06 12:36 UTC, luke-a-williams commented on jobs/clean_cqc_location_data.py
>          current_ons_df,
This function isn't being used anymore, can you remove it?

2024-03-06 12:36 UTC, luke-a-williams commented on jobs/clean_cqc_location_data.py
>      cqc_location_df = join_cqc_provider_data(cqc_location_df, cqc_provider_df)
This doesn't work in the glue pipeline, giving an  "import_date is ambiguous" error meaning there is 2 columns with the same name. The problematic code is as follows:
"""
  File "clean_cqc_location_data.py", line 178, in join_cqc_provider_data
    locations_df[Keys.import_date]
"""
In the cleaned provider data there is a column called `cqc_provider_import_date` you could use instead to see if that alleviates this issue?

2024-03-06 12:36 UTC, luke-a-williams commented on jobs/clean_cqc_location_data.py
>      cqc_location_df = join_cqc_provider_data(cqc_location_df, cqc_provider_df)
Or specify that it is the import_date that belongs to locations_df not just the key, maybe with an F.col(locations.import_date) or w.e. the column name is

2024-03-06 12:43 UTC, luke-a-williams commented on jobs/clean_cqc_location_data.py
>      cqc_location_df = join_cqc_provider_data(cqc_location_df, cqc_provider_df)
I don't know exactly where the problem occurs but the error seems to imply that at that point the location's df has two import_date columns. Maybe it could be coming from the join_ons_postcode_data_into_cqc_df function which does some stuff with import date too, but I don't fully understand exactly what's going on in that function without doing a deep dive myself!

2024-03-06 12:44 UTC, garypolzin commented on jobs/clean_cqc_location_data.py
>      cqc_location_df = join_cqc_provider_data(cqc_location_df, cqc_provider_df)
only importing selected columns on the import now which should fix this

2024-03-06 12:46 UTC, garypolzin commented on jobs/clean_cqc_location_data.py
>      cqc_location_df = join_cqc_provider_data(cqc_location_df, cqc_provider_df)
it was importing all columns from ons, so it was importing the ons partition keys as well as the ones already in the cqc df

2024-03-06 13:39 UTC, james-francis-MT commented on jobs/clean_ons_data.py
> +def prepare_current_ons_data(df: DataFrame) -> DataFrame:
Is the plan to use doc strings in functions that are just there to make the main function easier to read? I don't expect this function to be used anywhere else

2024-03-06 14:13 UTC, luke-a-williams commented
Re-running the job in the pipeline to see if the errors have been addressed

2024-03-06 15:25 UTC, merged