Setup estimate by job role script
NMDSdevopsServiceAdm/DataEngineering pull request #322
Opened 2024-03-12 15:27 UTC by james-francis-MT

# Description
Create a basic job for estimate ind cqc filled posts by job role job

# How to test
Will only be able to test in branch once https://trello.com/c/E55oXV1n/213-epic-9-refactor-estimatejobspy-for-new-pipeline-must has gone in 

# Developer checklist
- [ ] Unit test
- [ ] Linked to Trello ticket
- [ ] Documentation up to date

2024-03-15 15:09 UTC, garypolzin requested changes

2024-03-15 15:09 UTC, garypolzin commented on jobs/estimate_ind_cqc_filled_posts_by_job_role.py
> +def main(source: str, output_dir: str):
change `source `throughout to `estimated_ind_cqc_filled_posts_source`

change `output_dir `to `estimated_ind_cqc_filled_posts_by_job_role_destination`

2024-03-15 15:09 UTC, garypolzin commented on terraform/pipeline/glue.tf
> +  }
missing destination and change names to reflect the ones in the job

2024-03-15 15:09 UTC, garypolzin commented on terraform/pipeline/glue.tf
> +  datasets_bucket = module.datasets_bucket
include
glue_version    = "3.0"

2024-03-19 11:26 UTC, james-francis-MT commented
Runs successfully in my branch: https://eu-west-2.console.aws.amazon.com/gluestudio/home?region=eu-west-2#/editor/job/jf-estimate_ind_cqc_filled_posts_by_job_role_job/runs

2024-03-19 11:33 UTC, garypolzin approved these changes

2024-03-19 11:51 UTC, merged