Provider api key
NMDSdevopsServiceAdm/DataEngineering pull request #334
Opened 2024-03-18 16:45 UTC by luke-a-williams

# Description
https://trello.com/c/NBGWFkwP/24-epic-3-add-partner-code-to-api-calls-should
I have tried 2 different setups, shown in the commit history:
1) Having the Secret populated at build time. This is probably fine for this particular parameter, but since this sets a precedent and it is not known how visible circleci logs are for this parameter (security concerns around this) its not viable for more secure parameter requirements.
2) The implementation shown in this PR, which instead of loading the parameter at build time, loads the parameter at execution time. More secure, but slightly more involved in the terraform to implement (as it requires giving Glue the privilege to call from the parameter store)

# How to test
Runs have already been successful, however there hasn't been noticeable time saving. To prove the functionality is working as desired I will re-run on smaller samples and have print statements to prove the Url is constructed correctly.

# Developer checklist
- [x] Unit test
- [x] Linked to Trello ticket
- [ ] Documentation up to date

2024-03-18 16:55 UTC, garypolzin commented on jobs/bulk_download_cqc_locations.py
> +            "Source s3 directory for parquet CQC providers dataset",
CQC **locations** dataset

2024-03-18 16:57 UTC, garypolzin commented on utils/cqc_api.py
> +)
main reason for the partnercode was to speed up the rate limit so just checking that 400 is what we're staying at?

2024-03-18 17:56 UTC, MarionJHolloway requested changes
Looks like these are currently failing in branch?

2024-03-19 10:20 UTC, luke-a-williams commented on utils/cqc_api.py
> +)
Marion and i spoke about this yesterday, we tried putting it up to 2000 and didn't notice any improvement at all, so tried putting it back to 400 to see if our own rate limiting would help reduce the amount of sleeping. If it has helped, its marginal especially on the full runs. There are some slack threads in chat where I have visually compared the logs for the 2 different rate limited parameters

2024-03-19 10:22 UTC, luke-a-williams commented on utils/cqc_api.py
> +)
I've collected them on the trello ticket: https://trello.com/c/NBGWFkwP/24-epic-3-add-partner-code-to-api-calls-should

2024-03-19 10:23 UTC, luke-a-williams commented on utils/cqc_api.py
> +)
I'm investigating putting it back to 2k now on a small set now I know the partnercode is formatted correctly this morning

2024-03-19 11:10 UTC, luke-a-williams commented on utils/cqc_api.py
> +)
Yeah it doesn't seem to have any affect

2024-03-19 12:22 UTC, james-francis-MT commented on jobs/bulk_download_cqc_locations.py
> +        )["partner_code"],
Can this function call be moved outside the parameters?

2024-03-19 12:22 UTC, james-francis-MT commented on jobs/bulk_download_cqc_providers.py
> +        )["partner_code"],
same here

2024-03-19 12:22 UTC, james-francis-MT commented on utils/cqc_api.py
> +)
If it has made no difference then how do we know it is working at all?

2024-03-19 12:22 UTC, james-francis-MT commented on utils/cqc_api.py
> +        if e.response["Error"]["Code"] == "ResourceNotFoundException":
Perhaps a switch statement works best here

2024-03-19 12:22 UTC, james-francis-MT commented on utils/cqc_api.py
> +            return binary_secret_data
Probably worth writing some unit tests for this

2024-03-19 14:55 UTC, luke-a-williams commented on jobs/bulk_download_cqc_locations.py
> +        )["partner_code"],
Certainly

2024-03-19 14:58 UTC, luke-a-williams commented on jobs/bulk_download_cqc_providers.py
> +        )["partner_code"],
Actually that's a really good point, its retrieving it once per page with this setup so definitely makes sense to call it before entering the loop. Good spot.

2024-03-19 14:59 UTC, luke-a-williams commented on utils/cqc_api.py
> +        if e.response["Error"]["Code"] == "ResourceNotFoundException":
switch statements are a feature of python 3.10 and up. Our environment is on python version 3.9. Or did you mean something else?

2024-03-19 15:00 UTC, luke-a-williams commented on utils/cqc_api.py
> +            return binary_secret_data
100%, sorry it was taking me a while as I had to understand more about the kind of response packet that AWS could send back in this scenario. I have added tests in for this.

2024-03-19 15:06 UTC, james-francis-MT commented on utils/cqc_api.py
> +        if e.response["Error"]["Code"] == "ResourceNotFoundException":
wow 🤬 python is such a great language

2024-03-19 16:03 UTC, luke-a-williams commented on utils/cqc_api.py
> +        if e.response["Error"]["Code"] == "ResourceNotFoundException":
There isn't sad laughing emoji to respond to your comment hah

2024-03-19 16:05 UTC, luke-a-williams commented on utils/cqc_api.py
> +)
It's working on our end, in the sense that we are definitely sending a GET request to a url that now has a partnerCode parameter. Looking at the logs for key runs though, seems like the problem is their end. :(

2024-03-19 16:14 UTC, james-francis-MT commented on utils/cqc_api.py
> +)
Has someone taken an action to check with them?

2024-03-20 11:28 UTC, james-francis-MT approved these changes

2024-03-21 10:02 UTC, MarionJHolloway approved these changes

2024-03-21 10:23 UTC, merged