ML model - update care home model and made the features script less dynamic (regions)
NMDSdevopsServiceAdm/DataEngineering pull request #346
Opened 2024-03-25 16:59 UTC by garypolzin

# Description

### Care home model update
Updated care home model to the latest version (saved as 3.1.0 on s3)

### Regions in feature files
Previously the regions were compiled as a dynamic list based on what values were in that column - changed this so the region list is set (same process we use for rural/urban column) - this ensures that the number and order of region columns will match the ML model features

`add_rui_data_data_frame` function has been made more generic as it's used for rui and region-> `convert_categorical_variable_to_binary_variables_based_on_a_dictionary`

`explode_column_from_distinct_values` and `format_strings` are redundant now so have been removed

### Feature list test
I've returned the feature list at the end of main and put a test in place to ensure that it matches what we expect it to be

### Test run
[Ran successfully in branch](https://eu-west-2.console.aws.amazon.com/states/home?region=eu-west-2#/v2/executions/details/arn:aws:states:eu-west-2:344210435447:execution:use-new-ch-model-Ind-CQC-Filled-Post-Estimates-Pipeline:dc1c6a88-4525-4e27-90ae-6a640be7301b)

# Developer checklist
- [X] Unit test
- [X] Linked to Trello ticket
- [X] Documentation up to date

2024-03-26 14:09 UTC, luke-a-williams commented on terraform/pipeline/glue.tf
> +    "--care_home_model_source"        = "${module.pipeline_resources.bucket_uri}/models/care_home_filled_posts_prediction/3.1.0/"
I noticed the test for this job doesn't have it's model updated... does that matter? It is currently set to 0.0.1?

2024-03-26 14:19 UTC, garypolzin commented on terraform/pipeline/glue.tf
> +    "--care_home_model_source"        = "${module.pipeline_resources.bucket_uri}/models/care_home_filled_posts_prediction/3.1.0/"
the test has a dummy model which is saved as 0.0.1 - it's not testing the s3 file path is correct :)

2024-03-26 14:20 UTC, luke-a-williams reviewed
Checked that version numbers have been updated as per ticket instructions initially, now will check the tests

2024-03-26 14:45 UTC, luke-a-williams requested changes
Review comments for the prepare_care_home_ind_cqc_features part of this PR

2024-03-26 14:45 UTC, luke-a-williams commented on jobs/prepare_care_home_ind_cqc_features.py
> +
Why are you returning this? It's not being used anywhere within the script, and also the main method is defined to be returning a DataFrame not a list.

2024-03-26 14:45 UTC, luke-a-williams commented on jobs/prepare_care_home_ind_cqc_features.py
> +
I can see that you use it in the test script, but the test is testing that main produces a dataframe, not a list? It's a bit confusing

2024-03-26 14:45 UTC, luke-a-williams commented on tests/unit/test_prepare_care_home_ind_cqc_features.py
> +            "indicator_9",
If the order is not important, you can achieve this in a much shorter way by using `*list(RURAL_URBAN_INDICATOR_LOOKUP.keys())` such as in the following example of list extension:
`["Hi", *list(RURAL_URBAN_INDICATOR_LOOKUP.keys())]`
Gives:
`['Hi',
 'indicator_1',
 'indicator_2',
 'indicator_3',
 'indicator_4',
 'indicator_5',
 'indicator_6',
 'indicator_7',
 'indicator_8',
 'indicator_9',
 'indicator_10']`

2024-03-26 14:45 UTC, luke-a-williams commented on tests/unit/test_prepare_care_home_ind_cqc_features.py
> +            "ons_yorkshire_and_the_humber",
As above, can be shortened with `*list(REGION_LOOKUP.keys())`

2024-03-26 14:45 UTC, luke-a-williams commented on tests/unit/test_prepare_care_home_ind_cqc_features.py
> +            "service_9",
As above, as long as no numbers are missing and the order isn't important, can be shortened with:
`*list(SERVICES_LOOKUP.keys())`

2024-03-26 14:45 UTC, luke-a-williams commented on tests/unit/test_prepare_care_home_ind_cqc_features.py
> +        self.assertEqual(len(returned_feature_list), 51)
The main function is defined to output a dataframe, not a list, so if this is changed then this step would need refactoring to get the length of the list of columns of the dataframe, I think.

2024-03-26 14:45 UTC, luke-a-williams commented on tests/unit/test_prepare_care_home_ind_cqc_features.py
> +            51, [8, 11, 20, 21, 50], [1.0, 10.0, 1.0, 1.0, 1.0]
I'll admit I don't know much about this Vector at all, what's the significance of these number changes?

2024-03-26 14:51 UTC, luke-a-williams requested changes

2024-03-26 14:51 UTC, luke-a-williams commented on jobs/prepare_care_home_ind_cqc_features.py
> +        )
Why is this surrounded by paranthesis? Surely you can just do `features_df =  convert_categorical_variable_to_binary_variables_based_on_a_dictionary`

2024-03-26 14:51 UTC, luke-a-williams commented on jobs/prepare_care_home_ind_cqc_features.py
> +        )
Why is this surrounded by paranthesis? Surely you can just do features_df =  convert_categorical_variable_to_binary_variables_based_on_a_dictionary

2024-03-26 14:59 UTC, luke-a-williams commented on tests/unit/test_prepare_care_home_ind_cqc_features.py
> +            51, [8, 11, 20, 21, 50], [1.0, 10.0, 1.0, 1.0, 1.0]
51 columns wide df, and this is saying that the 8th, 11th, 20th, 21st, 50th columns have the entries in the list to the right.

2024-03-26 15:01 UTC, luke-a-williams commented on tests/unit/test_prepare_care_home_ind_cqc_features.py
> +            51, [8, 11, 20, 21, 50], [1.0, 10.0, 1.0, 1.0, 1.0]
I can't track this backwards to the columns easily that aren't empty but the test passes.

2024-03-26 15:04 UTC, luke-a-williams requested changes

2024-03-26 15:04 UTC, luke-a-williams commented on jobs/prepare_non_res_ind_cqc_features.py
> +
Same comment as for the other case, either return a dataframe or have the function defined to return a list.
It;s not being used in the script so you COULD do something only in the test to capture that list.

2024-03-26 15:11 UTC, luke-a-williams commented
Spoke to Gary, because the PR looks huge, and he has instructed me that most of the changes are re-names of scripts and adding and removing of tests based on the changed function calls... but the overall logic of the script hasn't changed much.

We resolved a lot of the things I'd reviewed already and conditional on the return type of main being up to scratch I'm happy with it as it is, since Gary wrote no new functionality

2024-03-27 08:27 UTC, garypolzin commented on jobs/prepare_care_home_ind_cqc_features.py
> +        )
not to note that this is auto formatted like this by black

2024-03-27 08:28 UTC, garypolzin commented on jobs/prepare_care_home_ind_cqc_features.py
> +        )
just to note that this is auto formatted like this by black

2024-03-27 10:55 UTC, luke-a-williams approved these changes
All of my comments have been addressed

2024-03-27 10:58 UTC, merged