Data quality checks demo
NMDSdevopsServiceAdm/DataEngineering pull request #349
Opened 2024-03-26 13:08 UTC by MarionJHolloway

# Description
https://trello.com/c/U9labRCK/314-create-demo-dq-test-script-for-merged-ind-cqc-data
This ticket:
* Sets up a demo data validation script and associated unit tests
* Updates the config to fit the requirements of using pydeequ
* Refactors how we call spark throughout - we need to only use one instance to manage the pydeequ config
* Adds the job and crawler to the step function - this job just produces an output, so failing the validation checks will not abort the pipeline.
* Refactors some code which no longer worked with the change in spark versions needed to run deequ

# How to test
Unit tests passing
Step function currently running in branch

# Developer checklist
- [x] Unit test
- [x] Linked to Trello ticket

2024-03-26 13:16 UTC, garypolzin commented on jobs/validate_merged_ind_cqc_data.py
> +from utils.column_names.ind_cqc_pipeline_columns import PartitionKeys as Keys
very minor but can merge these two

2024-03-26 13:20 UTC, garypolzin commented on terraform/modules/glue-job/optional-inputs.tf
> +    error_message = "Must be one of 1.0, 2.0, 3.0 or 4.0"
do we want this to just be 3 or 4 now 2 and below are no longer supported?

2024-03-26 13:24 UTC, garypolzin commented on tests/test_file_data.py
> +        ("1-000000001", date(2024, 1, 1), date(2024, 1, 1), "Independent", "Y", 10, "1", 1,10, date(2024, 1, 1)),
guessing the `1,10` will be throwing a formatting error in all of these rows, can you change to `1, 10`?

2024-03-26 13:35 UTC, garypolzin commented on utils/utils.py
> +from pyspark.sql import DataFrame, Column, Window
is there a reason why this has been separated?

2024-03-26 13:35 UTC, garypolzin commented on utils/utils.py
> +        # spark = SparkSession.builder.appName("sfc_data_engineering").getOrCreate()
should this be deleted now?

2024-03-26 14:02 UTC, MarionJHolloway commented on utils/utils.py
> +from pyspark.sql import DataFrame, Column, Window
Nope! Fixed :)

2024-03-27 11:18 UTC, luke-a-williams commented on Pipfile
> +pyspark = "==3.3.4"
This is more just a check, but does the order of these installs matter?

2024-03-27 11:29 UTC, luke-a-williams commented on terraform/pipeline/glue.tf
> +
I love that you can get a crawler to read the data quality checks dataframe and then query it in Athena

2024-03-27 11:55 UTC, james-francis-MT commented on Pipfile
> +pyspark = "==3.3.4"
Nah it doesn't matter

2024-03-27 12:03 UTC, luke-a-williams requested changes
Checks made:
- no job has a get_spark() call missed for refactor (P)
- Trello ticket objectives achieved (PPF - The 3rd test is currently failing on the dataset)
- Step function change has a successful run (P) 
- Step function change looks correct (P - I quite like running that validation step in parallel to the clean merge job not to waste time)
- Test data has full coverage (P)
- Tests have full coverage (F - missing tests for the `parse_data_quality_errors` function
- New job in appropriate location (P - I guess so, but I am curious if you think it would be better in a folder within the jobs directory to separate out the validation jobs from the main pipeline jobs?)
-

2024-03-27 12:03 UTC, luke-a-williams commented on tests/unit/test_validate_merged_ind_cqc_data.py
> +            "Value: 0.8888888888888888 does not meet the constraint requirement!"
That's interesting, so it's measuring a percentage coverage of the dataframe of non-nulls, and should be 1.0 or it errors? Am I understand that right?

2024-03-27 12:03 UTC, luke-a-williams commented on jobs/validate_merged_ind_cqc_data.py
> +        spark.stop()
I'm not familiar with this step, what is going on here?

2024-03-27 12:05 UTC, luke-a-williams commented
parse_data_quality_errors has no tests for it… but if this is a function which could be used in multiple validation jobs it might be better to abstract it?

2024-03-27 14:11 UTC, james-francis-MT commented on jobs/clean_cqc_location_data.py
> +            raise ValueError(
AnalysisException was changed from 3.3 -> 3.4

In 3.3 you have to give it a stack trace whereas in 3.4 you don't: 
https://issues.apache.org/jira/browse/SPARK-42342

https://github.com/apache/spark/pull/39882/files#diff-0a22271fecb7c4a38d8afe18ac8676546f1ad8fd221ccc0a5e4cfacdee869298R184

2024-03-27 14:13 UTC, james-francis-MT commented on jobs/clean_cqc_location_data.py
> +            raise ValueError(
Also this is the desciption of that error: 

    `Failed to analyze a SQL query plan.`

2024-03-27 14:14 UTC, james-francis-MT commented on tests/unit/test_validate_merged_ind_cqc_data.py
> +            self.spark.sparkContext._gateway.shutdown_callback_server()
_gateway can be None so just checking it is defined before calling a method on it

2024-03-27 14:21 UTC, james-francis-MT commented on jobs/validate_merged_ind_cqc_data.py
> +                f"DataFrame row count should be {cqc_location_df_size}",
Extra work needed to make this pass - I think this is just meant to be a bit of a demo of what can be done

2024-03-27 14:23 UTC, james-francis-MT commented on tests/unit/test_validate_merged_ind_cqc_data.py
> +os.environ["spark_version"] = "3.3"
Unfortunately it is needed for pydeequ

`With PyDeequ v0.1.8+, we now officially support Spark3 ! Just make sure you have an environment variable
SPARK_VERSION to specify your Spark version!`

2024-03-27 14:34 UTC, james-francis-MT commented
> parse_data_quality_errors has no tests for it… but if this is a function which could be used in multiple validation jobs it might be better to abstract it?

Any need for tests for a quick function that just has a couple of print statements?

2024-03-28 09:56 UTC, MarionJHolloway commented on terraform/pipeline/glue.tf
> +
Yeah, I think this will be useful for development

2024-03-28 10:00 UTC, MarionJHolloway commented on jobs/validate_merged_ind_cqc_data.py
> +                f"DataFrame row count should be {cqc_location_df_size}",
We could also have problems in the pipeline, which this validation is designed to detect. I think identifying the source of this would be a separate ticket

2024-03-28 10:04 UTC, MarionJHolloway commented on tests/unit/test_validate_merged_ind_cqc_data.py
> +        self.assertEqual(write_to_parquet_patch.call_count, 1)
It would be difficult to write that assertion in a scalable way, I'm not sure there is a way to count how many checks are in the script, and it should output one row per check. I can hard code a size in if you prefer, but I'm not sure if there's a better way.

2024-03-28 12:29 UTC, luke-a-williams approved these changes

2024-03-28 12:31 UTC, merged