WIP - Terraform environments
NMDSdevopsServiceAdm/DataEngineering pull request #35
Opened 2022-04-22 10:57 UTC by AdamProbert

2022-05-25 13:46 UTC, garypolzin approved these changes
impressive work!
can't see anything which stands out as being wrong or unusual

2022-05-25 13:46 UTC, garypolzin commented on terraform/pipeline/glue.tf
> +  job_parameters = {
Not sure if the parameters are right on this one?

2022-05-25 13:54 UTC, AdamProbert commented on terraform/pipeline/glue.tf
> +  job_parameters = {
Oh good spot, it should just be:
```
    "--prepared_locations_source" = ""
    "--destination"               = ""
````
right?

2022-05-25 15:40 UTC, AdamProbert commented on terraform/pipeline/glue.tf
> +  job_parameters = {
Have updated 👍

2022-05-25 17:46 UTC, LauraZM9 requested changes

2022-05-25 17:46 UTC, LauraZM9 commented on terraform/modules/glue-crawler/glue-crawler.tf
> +        "TableGroupingPolicy" : "CombineCompatibleSchemas"
Is there a reason for which you use both `=` and `:`? If not, I feel this should be more consistent.

2022-05-26 09:38 UTC, AdamProbert commented on terraform/pipeline/step-function.tf
> +}
Ahh nice, I did have a brief look for something like this. Have updated 🚀

2022-05-26 10:27 UTC, AdamProbert commented on README.md
> +
Yep, good shout. Have updated!

2022-05-26 10:34 UTC, LauraZM9 approved these changes
Great job, Adam! :tada:

2022-05-26 10:34 UTC, LauraZM9 commented on README.md
> +“What goes up must come down.” - Isaac Newton
Inspiring!

2022-05-26 10:34 UTC, LauraZM9 commented on README.md
> +cd terraform/pipeleine
you mean "pipeline"

2022-05-26 10:40 UTC, AdamProbert commented on README.md
> +cd terraform/pipeleine
ah of course I did, thank you!

2022-05-26 13:50 UTC, merged