Refactor ingest-asceds-dataset job
NMDSdevopsServiceAdm/DataEngineering pull request #38
Opened 2022-05-06 11:03 UTC by LauraZM9

Ticket: [[Epic4] Refactor ingest_ascwds_dataset job to be smarter](https://trello.com/c/rK0lK8PE)

Problem:
- The job was working with only one CSV file at a time

This PR: 
- The job can now be run on all the files from the S3 bucket filtered by a predefined **prefix** 
 e.g. `destination = "s3://sfc-data-engineering"`
`source = "s3://sfc-data-engineering-raw/domain=ASCWDS/dataset=workplace/`
- The delimiter is not required anymore as the job is able to determine the delimiter for a specific file before it reads it entirely

2022-05-16 16:08 UTC, AdamProbert requested changes
Fantastic PR!
Love the new util functions and the thoroughness of unit tests.
Great use of the `TWO_MB` variable too.

Main thing is to refactor the stubber class - I know we wrote this hastily together but could certainly do with some attention.

Couple of other smaller comments.

Great work 🚀 👊

2022-05-16 16:08 UTC, AdamProbert commented on tests/unit/test_utils.py
> +        stubber.add_response("list_objects", partial_response, expected_params)
With a refactored stubber class we can hopefully condense this down to 1 or 2 lines

2022-05-16 16:08 UTC, AdamProbert commented on tests/unit/test_utils.py
> +class MyStubberClass():
Needs a better name 🤣

2022-05-16 16:08 UTC, AdamProbert commented on utils/utils.py
> +from hashlib import sha3_384
Not sure this is used?

2022-05-16 16:08 UTC, AdamProbert commented on utils/utils.py
> +import re
Or this

2022-05-16 16:08 UTC, AdamProbert commented on utils/utils.py
> +    if num_bytes > TWO_MB:
love this! 💯 `TWO_MB`

2022-05-17 09:57 UTC, LauraZM9 commented on jobs/ingest_ascwds_dataset.py
> +    for key in objects_list:
I have done some changes to make it less confusing. Hope this is better now!

2022-05-17 10:50 UTC, LauraZM9 commented on tests/unit/test_utils.py
> +        self.assertTrue("s3://sfc-data-engineering-raw/domain=ASCWDS/dataset=workplace/version=0.0.1/year=2013/month=03/day=31/import_date=20130331/Provision - March 2013 - IND - NMDS-SC - ASCWDS for
Oh, you're right :sweat_smile:

2022-05-17 10:52 UTC, LauraZM9 commented on utils/utils.py
> +from hashlib import sha3_384
Unfortunately. there are a lot more :dizzy_face:

2022-05-17 14:11 UTC, JimmySunDance commented on tests/unit/test_utils.py
> +        body_data = """period|establishmentid|tribalid|tribalid_worker|parentid|orgid|nmdsid|workerid|wkplacestat|createddate
Does this example have to be so long?

2022-05-18 08:44 UTC, LauraZM9 commented on tests/unit/test_ingest_ascwds_dataset.py
These are all used.

2022-05-18 08:55 UTC, LauraZM9 commented on tests/unit/test_utils.py
> +        body_data = """period|establishmentid|tribalid|tribalid_worker|parentid|orgid|nmdsid|workerid|wkplacestat|createddate
No, good point.

2022-05-18 10:58 UTC, JimmySunDance approved these changes

2022-05-19 09:42 UTC, AdamProbert requested changes
🚀  Nice, great improvements! 
Couple more bits caught my eye though 👀

2022-05-19 09:42 UTC, AdamProbert commented on tests/unit/test_utils.py
> +            self.build_stubber_resource()
This is prone to bugs in the future.
Better to use explicit conditionals than `else` here.
Handle the "resource" type explicitly.


Also don't rely on string interpretation for equality - better to use constant variables.
e.g. CLIENT_TYPE = "client"

or you could try Enums:

`StubberType = Enum('client', 'resource')`

then access with `StubberType.client`

2022-05-19 09:42 UTC, AdamProbert commented on tests/unit/test_utils.py
> +        stubber.add_response("list_objects", partial_response, expected_params)
This is much cleaner, v.nice :)
Optional refactor: You could put the `stubber = StubberClass("resource")` into the `setUp` function for the test suite. Then access with `self.stubber` in each of the functions. For functions that don't use the "resource" type, you can override with a "client" type. Most of these look to use "resource" though 👍

2022-05-19 09:42 UTC, AdamProbert commented on tests/unit/test_utils.py
> +            'ContentLength': byte_string_length * 1000
why 1000? Perhaps a comment, or a well named variable?

2022-05-19 09:42 UTC, AdamProbert commented on tests/unit/test_utils.py
> +            'ContentLength': byte_string_length * 35
Why 35? Perhaps a comment, or well named variable

2022-05-19 15:37 UTC, AdamProbert approved these changes

2022-05-19 15:38 UTC, merged