Count postcode by la area
NMDSdevopsServiceAdm/DataEngineering pull request #390
Opened 2024-04-28 16:46 UTC by RoyPriceCS50

# Description

Created a function that adds a column with the count of the number of postcodes per LA area in the cleaned postcodes directory.

Function has two tests:
1 - check if the new column has been added and has the desired name.
2 - check the values in the new column are as expected (I didn't make a separate expected dataframe, I just indexed into the column and checked the value is what I expected.)

Link to trello ticket:
https://trello.com/c/cMlXwQ1v

# How to test

# Developer checklist
- [x] Unit test
- [x] Linked to Trello ticket
- [ ] Documentation up to date

2024-04-29 07:50 UTC, garypolzin commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +            schema=ONSTestSchema.expected_refactored_contemporary_schema,
we normally use the term 'expected' for known data that we want to compare the returned data to

Rather than creating it from scratch again, you can add the code below into test_file_schemas:
    your_new_schema_name = expected_refactored_contemporary_schema

so it's the same schema, but the name we see in the tests is more relevant

2024-04-29 07:57 UTC, garypolzin commented on jobs/split_pa_filled_posts_into_icb_areas.py
> +    postcode_directory_df = count_postcodes_per_la(postcode_directory_df)
good practice to have all of the read_from_parquet steps at the start so move this function (and replace?) # TODO 1 assuming this is that step

(not relevant here but also if you have multiple write_to_parquet function calls keep them all at the end)

2024-04-29 07:59 UTC, garypolzin commented on jobs/split_pa_filled_posts_into_icb_areas.py
> +    Window,
you can also add in `functions as F,` into this import as they are all from `pyspark.sql`

2024-04-29 08:03 UTC, garypolzin commented on jobs/split_pa_filled_posts_into_icb_areas.py
> +    ).orderBy([ONSClean.contemporary_ons_import_date, ONSClean.contemporary_cssr])
I don't think you need the square brackets here

2024-04-29 08:04 UTC, garypolzin commented on tests/test_file_data.py
> +import datetime
already imported datetime (row above)

2024-04-29 08:05 UTC, garypolzin commented on tests/test_file_data.py
> +        ("AB10AD", datetime.date(2024,1,1), "cssr2", "region1", "subicb2", "icb3", "icb_region2", None, "51.23456", "-.12345", "123", "E010123", "E020123", "Rural village", "E010123", "E020123", "pco
as we've already got `from datetime import date` you can remove `datetime.` from these rows and just have `date(2024,1,1)`

2024-04-29 08:06 UTC, MarionJHolloway requested changes
A really good first attempt! There's a bit more work to do to finish this off, but I'm really impressed with how far along you've managed to get in independently, well done!

Happy to talk through these comments on Tuesday if that would help.

2024-04-29 08:06 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +        print(column_index)
remove?

2024-04-29 08:06 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +        column_index = job.count_postcodes_per_la(
You don't need this line - you can just use the column name string in square brackets to access the column. This will work, but is just extra code we don't need.

2024-04-29 08:06 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +class CountPostcodesPerLA(SplitPAFilledPostsIntoICBAreas):
You will also need a test to check behaviour if we have windows with duplicate postcodes. Currently, the function would count the duplicates, which is a behaviour we don't want (we'd be counting the same geographical area twice)

2024-04-29 08:21 UTC, garypolzin reviewed
added a couple of 'good practice' comments but on the whole it's a really impressive PR - it's way more complicated than the early PRs I was putting in and I defo had more comments back!

don't be daunted by the amount of comments either, they'll drop off really quickly :)

2024-04-30 09:50 UTC, RoyPriceCS50 commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +            schema=ONSTestSchema.expected_refactored_contemporary_schema,
Is this expected data?
I put the cleaned postcode directory into a dataframe as "test data".
I'm not making a bunch of separate test_data rows with an an expected result from the function.
I copied stuff from test _clean_cqc_provider_data.

2024-04-30 10:10 UTC, garypolzin commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +            schema=ONSTestSchema.expected_refactored_contemporary_schema,
yea that's right, it's not expected data, but the schema has 'expected' in it so I wasn't sure if it was or not

give me a shout if this doesn't make sense!

2024-04-30 11:49 UTC, RoyPriceCS50 commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +            schema=ONSTestSchema.expected_refactored_contemporary_schema,
I had to make an expected dataframe in the end, so i've got a test dataframe, a returned df and compare that to an expected df.

2024-04-30 11:52 UTC, RoyPriceCS50 commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +class CountPostcodesPerLA(SplitPAFilledPostsIntoICBAreas):
Turns out the window function doesn't allow a count_distinct method.
I get a set from the window, then get the size of that set.

2024-04-30 11:58 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +class CountPostcodesPerLA(SplitPAFilledPostsIntoICBAreas):
I asked Roy to add it in because if we do have duplicates, I don't want the DPR stuff to break. We don't touch it very often and this will affect the weighting of our estimates. 

BTw - you're solution is very elegant Roy, well done!

2024-04-30 12:01 UTC, RoyPriceCS50 commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +class CountPostcodesPerLA(SplitPAFilledPostsIntoICBAreas):
google is my friend

2024-04-30 12:01 UTC, garypolzin commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +class CountPostcodesPerLA(SplitPAFilledPostsIntoICBAreas):
duplicate postcodes will destroy our whole pipeline to be fair! but all good :)

2024-04-30 12:07 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +class CountPostcodesPerLA(SplitPAFilledPostsIntoICBAreas):
Yeah, I am itching to get the validaiton in!

2024-04-30 12:17 UTC, garypolzin commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +class CountPostcodesPerLA(SplitPAFilledPostsIntoICBAreas):
slightly less important that one anyway as I clean that file before importing into s3

2024-04-30 13:29 UTC, MarionJHolloway requested changes
Last few tweaks and you're good :)

2024-04-30 13:29 UTC, MarionJHolloway commented on jobs/split_pa_filled_posts_into_icb_areas.py
> +        DPColNames.SUM_POSTCODES_PER_LA,
Can you rename this column to accurately reflect what's in it?

2024-04-30 13:29 UTC, MarionJHolloway commented on utils/direct_payments_utils/direct_payments_column_names.py
> +    SUM_POSTCODES_PER_LA: str = "sum_postcodes_per_la"
Column name will need updating here too

2024-04-30 16:41 UTC, RoyPriceCS50 commented on utils/direct_payments_utils/direct_payments_column_names.py
> +    SUM_POSTCODES_PER_LA: str = "sum_postcodes_per_la"
I've renamed the column.

2024-04-30 16:41 UTC, RoyPriceCS50 commented on jobs/split_pa_filled_posts_into_icb_areas.py
> +        DPColNames.SUM_POSTCODES_PER_LA,
Renamed it, Kept missing a few places in the code but passing tests now.

2024-05-01 07:46 UTC, merged