Join pa filled posts into hybrid ratio table
NMDSdevopsServiceAdm/DataEngineering pull request #406
Opened 2024-05-10 18:04 UTC by RoyPriceCS50

# Description
Added three new functions to PA estimates split by ICB area job.
One adds a date column to the PA estimates (set to 31st March then estimate year).
One gets the appropriate date for joining the PA estimates to the postcode proportions table (Contemporary geographies as at PA estimate year).
Then PA estimates (right) are joined to the table of postcode proportions (left) based on contemporary import date and LA area, using left join.

Tests are passing.

Trello ticket:   https://trello.com/c/lVLiXspR

# How to test

# Developer checklist
- [x] Unit test
- [x] Linked to Trello ticket
- [ ] Documentation up to date

2024-05-13 10:22 UTC, MarionJHolloway requested changes
This generally looks really good! There's a few things to fix with the tests though. Remember that your tests don't just make sure your functions work as expected, they also define what your code does, so making them clear and easy to follow is important for whoever works on this next. Tidying up how you name variables and being clear about what each function needs as a minimum input and output will make this easier to read.

2024-05-13 10:22 UTC, MarionJHolloway commented on tests/test_file_schemas.py
> +            StructField("Group", StringType(), True),
What is this column for?

2024-05-13 10:22 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +            TestData.expected_deduplicated_importdate_hybrid_and_la_and_ratio_rows,
importdate -> import_date

2024-05-13 10:22 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +    def test_align_dates_from_pa_filled_posts_to_postcode_proportions_has_expected_values(
This is thoroughly tested in cleaning utils, so this is duplicating a previous test, you can remove it.

2024-05-13 10:22 UTC, MarionJHolloway commented on tests/test_file_schemas.py
> +    sample_pa_filled_posts_before_being_joined_schema = StructType(
Can you clean up these names a bit so it's clear which function they are testing?

2024-05-13 10:22 UTC, MarionJHolloway commented on tests/test_file_schemas.py
> +            *sample_postcode_proportions_before_joining_pa_filled_posts_schema,
I'm not sure how these schemas are supposed to link up? This looks like the join is adding the filled posts and year and date columns, which is not what we want? Surely it should be sample_pa_filled_posts_before_being_joined_schema plus the column we are joining in?

2024-05-13 10:22 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +        ).select(
Why are you selecting certain columns here? Is the function including columns that we don't want it to?

2024-05-13 10:22 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +        self.sample_postcode_proportions_before_joining_pa_filled_posts_df = self.spark.createDataFrame(
You don't need such complicated df names here. sample_postcode_df, sample_dpr_df, returned_df and expected_df are sufficient to understand what the test is testing. The lengthy names are quite hard to read and don't add a meaningful distinction between the datasets

2024-05-14 08:01 UTC, RoyPriceCS50 commented on tests/test_file_schemas.py
> +            StructField("Group", StringType(), True),
In the PR's that Gary reviewed he said it's useful to have a sorting column.
Realise now I should have called it "ordering_column" or something relevant to what it is.

2024-05-14 14:19 UTC, RoyPriceCS50 commented
I've actioned the issues raised and gone through previous tests to remove usage of an "ordering column".
All tests passing.

2024-05-16 08:24 UTC, MarionJHolloway requested changes
Looking much cleaner! Once these smaller changes are made, can you run the code in branch and make sure it completes successfully, then I will approve.

2024-05-16 08:24 UTC, MarionJHolloway commented on tests/test_file_schemas.py
> +    sample_postcode_proportions_before_joining_pa_filled_posts_schema = StructType(
If the schemas are the same, you don't need to explode them, you can just do:
schema b = schema a

2024-05-16 08:24 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +            TestData.sample_pa_filled_post_rows,
Can you make sure you are consistent with filled_post (singular) or filled_posts (plural). I would suggest making all instances plural, because we're unlikely to ever have one filled post. You probably want to run some find and replace searches to get all of these, I've spotted it in a few names

2024-05-16 08:24 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +        self.expected_after_adding_date_from_year_column_df = self.spark.createDataFrame(
I generally like to mirror the function name in the tests data variable names. I think this makes it easier to work out which data is testing which function when you're just looking at the data/ schemas. I think the names you've got generally make sense, but it's something you might want to consider in terms of making your code cleaner and easier to read.

2024-05-16 08:24 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +class JoinPaFilledPostsToPostcodeProportions(SplitPAFilledPostsIntoICBAreas):
Looks like this should be HybridArea not postcode?

2024-05-16 08:24 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +    def test_join_pa_filled_posts_to_hybrid_area_proportions_has_expected_column_count(
Test names are the one place you do want very descriptive names. So instead of the generic "expected column count" try to explain what you are actually testing, e.g. "adds two columns". This applies to some of the tests below as well.

2024-05-16 08:24 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +    def test_join_pa_filled_posts_to_hybrid_area_proportions_has_no_duplicate_columns(
I like this! A sensible thing to check for a join and neatly written, well done!

2024-05-16 08:24 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +        sort_by_list = [
Nice abstraction. This makes it really easy to see which columns are the index columns, but doesn't clutter up your code.

2024-05-16 08:24 UTC, MarionJHolloway commented on jobs/split_pa_filled_posts_into_icb_areas.py
> +        F.make_date(DPColNames.YEAR, F.lit("03"), F.lit("31")),
Probably worth abstracting these magic strings. I think other values are stored somewhere so they can probably go in the same place.

2024-05-17 09:38 UTC, MarionJHolloway approved these changes
well done!

2024-05-17 09:51 UTC, merged