Apply ratio to calc icb filled posts
NMDSdevopsServiceAdm/DataEngineering pull request #413
Opened 2024-05-17 16:08 UTC by RoyPriceCS50

# Description
Added a function to create a new column with the estimated number of PA's in each ICB. The column is the estimate of PA's in each CSSR multiplied by the proportion of postcodes per ICB within each CSSR.

There is an issue with the join, leading to blank rows in the joined columns. The issue is caused by the CSSR names being different in the PA estimates to the cleaned postcode file.
One of the joined columns is used as a partition key when writing to parquet, and because this has blanks, this causes the job to run very slowly (but succeeds).

# How to test
Tests are passing.
It runs successfully in branch, but takes ~25 minutes.
Link to run:
https://eu-west-2.console.aws.amazon.com/gluestudio/home?region=eu-west-2#/editor/job/apply-ratio-to-calc-icb-filled-split_pa_filled_posts_into_icb_areas_job/runs

Link to Trello:    https://trello.com/c/CiBeY4ja

# Developer checklist
- [x] Unit test
- [x] Linked to Trello ticket
- [ ] Documentation up to date

2024-05-20 07:47 UTC, MarionJHolloway requested changes
A few small changes to make and a couple of questions about your code :) This was generally really good though, well done!

2024-05-20 07:47 UTC, MarionJHolloway commented on tests/test_file_data.py
> +        (1.00000, 100.2),
What are you testing that is unique with each of the top three rows of this data frame? You might want to consider testing the output if none exists in the first column or both columns.

2024-05-20 07:47 UTC, MarionJHolloway commented on jobs/split_pa_filled_posts_into_icb_areas.py
> +        postcode_directory_df,
At some point, this stops really being the postcode directory anymore! Now that most of the job is coded up, have a think about how you want to name your variables in main. Try to create a variable name that describes what you are actually outputting here.

2024-05-20 07:47 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +            partitionKeys=[ONSClean.contemporary_cssr],
Note - this is a temporary change to allow the data to save currently. This will be reverted in a later PR.

2024-05-20 07:47 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +class ApplyIcbProportionsToPAEstimates(SplitPAFilledPostsIntoICBAreas):
Standardise capitalisation (Icb vs. ICB)

2024-05-20 07:47 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +        for i in range(len(returned_rows)):
Why did you choose to write this as a loop over lines instead of comparing one data frame to another?

2024-05-21 08:40 UTC, RoyPriceCS50 commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +        for i in range(len(returned_rows)):
It was how I tested during previous approved PR on CreateRatioBetweenColumns.
I've changed it in this test, but not in the previous test in CreateRatioBetweenColumns.
I tried it in the previous test, but kept getting a 'failed with errors' because unsupported types list and list, even though in both tests they use lists.

2024-05-21 09:23 UTC, RoyPriceCS50 commented
I've actioned the comments in my latest commit.

2024-05-21 10:43 UTC, MarionJHolloway commented on tests/unit/test_dpr_split_pa_filled_posts_into_icb_areas.py
> +        for i in range(len(returned_rows)):
It's not wrong to use the for loop. If you want to be able to check each row separately, it works quite well, particularly if you made the string into an f-string that told you which row was failing. Have a think about both tests and decide if checking each row separately is useful in each case. If you're getting errors let me know and we can debug together.

2024-05-23 11:20 UTC, merged