Add checks of location and provider id length
NMDSdevopsServiceAdm/DataEngineering pull request #448
Opened 2024-06-11 14:02 UTC by MarionJHolloway

# Description
Add checks of location and provider ID length

# How to test
Unit tests passing
Run in branch: https://eu-west-2.console.aws.amazon.com/states/home?region=eu-west-2#/v2/executions/details/arn:aws:states:eu-west-2:344210435447:execution:clean-provider-id-column-Ind-CQC-Filled-Post-Estimates-Pipeline:86021c65-63fb-4900-ac83-45330cfd351b
https://eu-west-2.console.aws.amazon.com/states/home?region=eu-west-2#/v2/executions/details/arn:aws:states:eu-west-2:344210435447:execution:clean-provider-id-column-Silver-Validation-Pipeline:24e8a1f6-53c4-46b6-94c4-3f9f6a148b6e

2024-06-12 11:03 UTC, RoyPriceCS50 reviewed
Looks alright to me

2024-06-12 15:13 UTC, garypolzin approved these changes
one very, very minor comment but otherwise looks like it's doing everything we discussed!

2024-06-12 15:13 UTC, garypolzin commented on utils/validation/validation_utils.py
>  from pyspark.sql.dataframe import DataFrame
may as well merge these 2
from pyspark.sql import DataFrame, functions as F

2024-06-12 15:15 UTC, garypolzin commented
> Looks alright to me.
> 
> How did you decide on the string length limits of 3 to 14?
> 
> Hard to see the changes specific to this PR amongst all the impute date stuff.

I made them up based on very little investigation - easy enough to amend if they don't work!

2024-06-12 15:18 UTC, garypolzin requested changes
sorry thought of something after approving :)

2024-06-12 15:18 UTC, garypolzin commented on utils/validation/validation_rules/locations_api_cleaned_validation_rules.py
> +            Validation.provider_id_length: 14,
if we are using these 3/14 in various places then it might be better setting their value in one place and referring to that

there's a good chance that if we ever need to update these we'll forget to update the ones in the providers_api_cleaned_validation_rules job and vice versa

2024-06-13 09:59 UTC, garypolzin approved these changes

2024-06-13 10:19 UTC, merged