Update non res with dormancy features
NMDSdevopsServiceAdm/DataEngineering pull request #475
Opened 2024-07-04 14:14 UTC by MarionJHolloway

# Description
This PR updates the list of features in the non-res with dormancy features job to include time open. Unit tests and validation were also added.
A small change was made to the clean CQC location job so that the imputed registration date is now in a date format instead of string format.

# How to test
Unit tests passing
Run successfully in branch: https://eu-west-2.console.aws.amazon.com/states/home?region=eu-west-2#/v2/executions/details/arn:aws:states:eu-west-2:344210435447:execution:update-non-res-with-dormancy-f-Ind-CQC-Filled-Post-Estimates-Pipeline:f08b4719-d9f5-4b95-be50-50a2ce05bffc

# Developer checklist
- [x] Unit test
- [x] Linked to Trello ticket: https://trello.com/c/zwIJq1KL/611-epic-1-update-features-job-for-non-residential-ascwds-with-dormancy-model-must
- [x] Documentation up to date

2024-07-04 14:56 UTC, garypolzin requested changes
looks great, couple of comments but mostly optional

2024-07-04 14:56 UTC, garypolzin commented on utils/validation/validation_rules/non_res_ascwds_inc_dormancy_ind_cqc_features_validation_rules.py
> +        },
add validations for time open too?

shouldn't be negative, no nulls

2024-07-04 14:56 UTC, garypolzin commented on utils/features/helper.py
> +def add_time_open_into_df(df: DataFrame, new_col_name: str) -> DataFrame:
do you think this needs to be more specifically named, such as
number_of_days_between_registration_date_and_file_date / length_of_time_registered_for
(it's the date of registration, not 'open' - could have been open longer but as a non-cqc place)

2024-07-04 14:56 UTC, garypolzin commented on utils/column_values/categorical_columns_by_dataset.py
>      care_home_column_values = CareHome(
does this one need renaming to match the format in the one below:
care_home_column_care_home_values

2024-07-05 07:41 UTC, MarionJHolloway commented on utils/features/helper.py
> +def add_time_open_into_df(df: DataFrame, new_col_name: str) -> DataFrame:
I went for time registered because it seemed more accurate but still concise

2024-07-05 09:25 UTC, garypolzin approved these changes

2024-07-05 09:35 UTC, merged