Cqc coverage add in ascwds
NMDSdevopsServiceAdm/DataEngineering pull request #476
Opened 2024-07-05 14:50 UTC by RoyPriceCS50

# Description
Added new function to merge_coverage_data job.
Function adds 1 column called "in_ascwds" which shows 0 or 1 if row has an asc-wds establishmentid.

# How to test
Unit tests passing.
Link to successful run in Glue: https://eu-west-2.console.aws.amazon.com/gluestudio/home?region=eu-west-2#/editor/job/cqc-coverage-add-in-ascwds-merge_coverage_data_job/runs

Link to Trello: https://trello.com/c/TNTEISLq

# Developer checklist
- [x] Unit test
- [x] Linked to Trello ticket
- [ ] Documentation up to date

2024-07-05 15:15 UTC, MarionJHolloway commented on jobs/merge_coverage_data.py
> +    MergeCoverageDataColumns as MergeColumns,
Maybe just "Coverage Columns"? We might extend this work one day and add another job, but the column names would be heritable.

2024-07-05 15:16 UTC, MarionJHolloway commented on jobs/merge_coverage_data.py
> +        F.when(F.isnull(AWPClean.establishment_id), 0).otherwise(1),
You can add these to the column values script. I can show you how that's set up and how to use it.

2024-07-05 15:17 UTC, MarionJHolloway commented on tests/unit/test_merge_coverage_data.py
> +            len(self.sample_in_ascwds_df.columns) + 1,
Length of expected df? That removes the need for the magic number here

2024-07-05 15:18 UTC, MarionJHolloway commented on jobs/merge_coverage_data.py
> +) -> DataFrame:
Our feedback from the ONS was to improve our documentation, so I'm going to start pushing for us to write doc strings for functions we create or modify. I can talk you through this if you want.

2024-07-09 08:15 UTC, RoyPriceCS50 commented on jobs/merge_coverage_data.py
> +) -> DataFrame:
Add doc strings to only my function or the whole job script?

2024-07-09 09:38 UTC, MarionJHolloway commented on jobs/merge_coverage_data.py
> +) -> DataFrame:
Seeing as there's only 2 here, it might be worth doing both.

2024-07-09 10:02 UTC, RoyPriceCS50 commented on jobs/merge_coverage_data.py
> +        F.when(F.isnull(AWPClean.establishment_id), 0).otherwise(1),
Think i've figured this out and pushed changes in my branch. Can show it in the meeting this afternoon.

2024-07-09 14:20 UTC, MarionJHolloway requested changes
Just a few tweaks and then it should be over the line, well done!

2024-07-09 14:20 UTC, MarionJHolloway commented on jobs/merge_coverage_data.py
> +    Takes specific columns from the cleaned CQC locations dataframe and joins specific columns from the ASC-WDS reconciliation dataframe.
All columns? Yes, the job specifies specific columns, but the function would still work the same if you changed the list of columns at the top of the script.

Also, it's worth being specific here about the fact that it aligns import dates and joins on aligned import dates and location id.

2024-07-09 14:20 UTC, MarionJHolloway commented on jobs/merge_coverage_data.py
> +        cqc_location_df (DataFrame): A dataframe of cleaned CQC locations.
Specify any columns that are essential for the function to work (i.e. location id and cqc location import date). This is important information for anyone using the function.

2024-07-09 14:20 UTC, MarionJHolloway commented on jobs/merge_coverage_data.py
> +        cqc_location_import_date_column (String): A string refering to the import date column in the clean CQC locations dataframe.
You want to be specific that this string is the **name** of the column

2024-07-09 14:20 UTC, MarionJHolloway commented on jobs/merge_coverage_data.py
> +        merged_coverage_df (DataFrame): A dataframe of CQC locations with ASC-WDS columns joined via locationid.
Probably worth adding that it needs estab id

2024-07-09 14:20 UTC, MarionJHolloway commented on tests/test_file_data.py
> +    # fmt: off
You don't need to turn the linter off for these rows, they are short anyway :)

2024-07-09 14:20 UTC, MarionJHolloway commented on utils/column_values/categorical_columns_by_dataset.py
> +from utils.column_names.coverage_columns import CoverageColumns
Not needed

2024-07-09 14:20 UTC, MarionJHolloway commented on utils/column_values/categorical_columns_by_dataset.py
> +    InAscwds,
Not needed

2024-07-09 15:04 UTC, MarionJHolloway approved these changes
Looks good!

2024-07-09 15:30 UTC, merged