CQC care directory to parquet
NMDSdevopsServiceAdm/DataEngineering pull request #48
Opened 2022-05-30 10:12 UTC by garypolzin

imports old Excel format of CQC files which contains both location and provider data in one file

splits out into 2 parquet files to match the format of the CQC Locations API and Providers API

2022-05-30 14:02 UTC, LauraZM9 requested changes

2022-05-30 14:19 UTC, LauraZM9 commented on tests/test_data/example_cqc_care_directory.csv
> +locationid,registrationdate,carehome,name,type,mainphonenumber,registered_manager_name,website,numberofbeds,region,localauthority,postaladdressline1,postaladdressline2,postaladdresstowncity,postaladd
I recently found this [library](https://databrickslabs.github.io/dbldatagen/public_docs/APIDOCS.html#creating-data-set-with-pre-existing-schema) that allows you to generate test data using a schema. I was planning to use it for the worker dataset. It might be a good idea if you have the schema for your data.

2022-05-30 14:26 UTC, garypolzin commented on tests/test_data/example_cqc_care_directory.csv
> +locationid,registrationdate,carehome,name,type,mainphonenumber,registered_manager_name,website,numberofbeds,region,localauthority,postaladdressline1,postaladdressline2,postaladdresstowncity,postaladd
yea that's what I do in the main script

I need to make sure my output matches the CQC API schema so I create an empty dataset using the API schema, then union into it - I don't have a schema for the raw data though unfortunately

2022-05-30 14:31 UTC, LauraZM9 commented on tests/test_data/example_cqc_care_directory.csv
> +locationid,registrationdate,carehome,name,type,mainphonenumber,registered_manager_name,website,numberofbeds,region,localauthority,postaladdressline1,postaladdressline2,postaladdresstowncity,postaladd
I manually wrote one :sweat_smile:

2022-05-30 14:54 UTC, garypolzin commented on jobs/ingest_cqc_care_directory.py
> +def regulatedactivities_to_struct(df):
it is yes :)
the column name in the raw data is called 'regulatedactivities' so wasn't sure what takes priority, ease of reading each word or to say this is converting the column regulatedactivities to a struct

2022-05-30 15:31 UTC, LauraZM9 commented on jobs/ingest_cqc_care_directory.py
> +def regulatedactivities_to_struct(df):
I think readability is important, it might be worth also renaming the column if it's confusing.

2022-06-08 11:32 UTC, garypolzin commented on jobs/ingest_cqc_care_directory.py
> +        return_datasets.append(output_provider_df)
must provide a destination now

2022-06-09 10:24 UTC, LauraZM9 approved these changes
Great job, Gary! 👍

2022-06-09 10:24 UTC, LauraZM9 commented on jobs/ingest_cqc_care_directory.py
> +    export_parquet_files(provider_df, provider_destination, location_df, location_destination)
If you decide to reduce this function, in main it will look like this:
```suggestion
    export_parquet_files(provider_df, provider_destination)
    export_parquet_files(location_df, location_destination)
```

2022-06-09 10:24 UTC, LauraZM9 commented on jobs/ingest_cqc_care_directory.py
> +    print("Reading CSV from {source}")
This is missing the f in front, so it will not do string interpolation.
```suggestion
    print(f"Reading CSV from {source}")
```

2022-06-09 13:52 UTC, elcorbs approved these changes

2022-06-09 14:48 UTC, merged