Add latest cqc rating
NMDSdevopsServiceAdm/DataEngineering pull request #481
Opened 2024-07-11 14:28 UTC by RoyPriceCS50

# Description
Added two functions to mere_coverage_data job. One for filtering cqc ratings to latest only. One for applying the filter and then joining the ratings to coverage dataframe.
The join adds the latest overall rating and the rating date to the coverage dataframe.

Also changed the cqc ratings column name script so that date = "rating_date" instead of "date".

Link to Trello:  https://trello.com/c/uWWQi5a3

# How to test
Unit tests are passing.

Link to successful run in Glue: https://eu-west-2.console.aws.amazon.com/gluestudio/home?region=eu-west-2#/editor/job/add-latest-cqc-rating-merge_coverage_data_job/runs

# Developer checklist
- [x] Unit test
- [x] Linked to Trello ticket
- [ ] Documentation up to date

2024-07-11 14:58 UTC, MarionJHolloway requested changes
Well done! You're skills are really improving :)

Happy to chat through the comments on a call if that's easier.

2024-07-11 14:58 UTC, MarionJHolloway commented on utils/column_values/categorical_column_values.py
> +    latest_rating: int = 1
So these are from a different column in the same dataset. They will need a new class for that column.

2024-07-11 14:58 UTC, MarionJHolloway commented on jobs/merge_coverage_data.py
> +def keep_only_latest_cqc_ratings(
It's generally good practice to use descriptive verbs for function names. Most of our functions designed to filter start with "filter_..." It just makes it easier to scan the code and understand what transformation has been performed.

2024-07-11 14:58 UTC, MarionJHolloway commented on jobs/merge_coverage_data.py
> +     Join latest rating to coverage dataframe using locationid as key.
Formatting - you have a space at the start of the comment

2024-07-11 14:58 UTC, MarionJHolloway commented on terraform/pipeline/glue.tf
> +    "--cqc_ratings_source"                  = "${module.datasets_bucket.bucket_uri}/domain=SfC/dataset=cqc_ratings/"
You will need to update the step function in terraform too!

2024-07-11 14:58 UTC, MarionJHolloway commented on tests/unit/test_merge_coverage_data.py
> +        self.sample_cqc_ratings_df = self.spark.createDataFrame(
Is this not the same test data and schema as in row 44? Best to create it once and reuse.

2024-07-11 14:58 UTC, MarionJHolloway commented on tests/unit/test_merge_coverage_data.py
> +class KeepOnlyLatestCqcRatingTests(unittest.TestCase):
Change this to inherit from MergeCoverageDatasetTests (and the other test class you made) so you don't have to duplicate your data :)

2024-07-11 14:58 UTC, MarionJHolloway commented on tests/test_file_data.py
> +        ("1-000000001", None, "Good", None),
Well done for testing with null values

2024-07-11 14:58 UTC, MarionJHolloway commented on tests/unit/test_merge_coverage_data.py
> +        distinct_latest_rating_rows = latest_rating_column_df.distinct().collect()
Why do you use distinct here?

2024-07-11 14:58 UTC, MarionJHolloway commented on tests/unit/test_merge_coverage_data.py
> +            sorted(list(set(self.returned_df.columns))),
Nice!

2024-07-11 15:05 UTC, RoyPriceCS50 commented on tests/unit/test_merge_coverage_data.py
> +        distinct_latest_rating_rows = latest_rating_column_df.distinct().collect()
The dataframe has only 1 column, the latest rating flag.
Distinct removes duplicate values, so I want to only see 1's remaining. If that's true, then I only have 1 row left and the value of that row is 1.

2024-07-12 09:30 UTC, MarionJHolloway requested changes
Because you've updated the step function, can you run the step function in branch to test that's all wired up properly and add a link to it in the PR description. There's also one small tweak to wording in the tests.  After that, I can approve :)

2024-07-12 09:30 UTC, MarionJHolloway commented on tests/unit/test_merge_coverage_data.py
> +    def test_filter_for_latest_cqc_ratings_only_has_expected_row_count(self):
I don't think you need "only" in this test name :)

2024-07-12 10:42 UTC, MarionJHolloway approved these changes
Well done!

2024-07-12 10:46 UTC, merged