Remove specialist colleges [WIP]
NMDSdevopsServiceAdm/DataEngineering pull request #484
Opened 2024-07-15 11:34 UTC by MarionJHolloway

# Description
This PR adds a function to the clean CQC locations job which removes rows where the primary service type is specialist college.
Unit tests added.
Updates made to validation row count.

# How to test
Unit tests passing
Run in branch here:

# Developer checklist
- [x] Unit test
- [x] Linked to Trello ticket: https://trello.com/c/BKn6NzwK/496-epic-7-remove-specialist-colleges-from-data-must
- [x] Documentation up to date

2024-07-17 08:04 UTC, garypolzin requested changes
The current rules for specialist college are that they are removed if it is the 'only' service they offer - I don't know if the ordering of the gac_service_types column implies how much of something they offer (that's not how we allocate primary_service_type anyway)

2024-07-18 13:50 UTC, garypolzin requested changes
feel free to give me a call if the below doesn't make sense, I clicked something by accident and I can't see half of the comments I made so hopefully they all make sense!

2024-07-18 13:50 UTC, garypolzin commented on tests/unit/test_clean_cqc_location_data.py
> +        self.assertEqual(self.returned_df.collect(), self.expected_df.collect())
probably safest to sort these

2024-07-18 13:50 UTC, garypolzin commented on tests/unit/test_clean_cqc_location_data.py
> +        self.assertEqual(returned_df.collect(), expected_df.collect())
sort

2024-07-18 13:50 UTC, garypolzin commented on tests/unit/test_clean_cqc_location_data.py
> +        )
if the function deletes every single row then it will have less rows so it's quite ambiguous, better to test that returned cols match expected like we usually do

2024-07-18 13:50 UTC, garypolzin commented on tests/unit/test_clean_cqc_location_data.py
> +    def test_remove_specialist_colleges_does_not_drop_rows_where_specialist_college_is_the_first_service_listed(
might need to specify that this is only relevant when they have multiple services - if they only have one service then college will be the first, and we want to remove them

2024-07-18 13:50 UTC, garypolzin commented on tests/unit/test_clean_cqc_location_data.py
> +    ):
instead of first/not-first, we're actually wanting to know if it's the only/not only

2024-07-18 13:50 UTC, garypolzin commented on jobs/clean_cqc_location_data.py
> +        | (df[CQCLClean.services_offered].isNull())
this does work but I personally find the tests a bit confusing refering to whether it's the first or not

might be able to change the test wording and keep this function as it is, or change to the below
(keep if 1 service and it's not a college, or keep if more than service, or null)

```
        ((F.size(df[CQCLClean.services_offered]) = 1) & (df[CQCLClean.services_offered][0] != Services.specialist_college_service))
        | (F.size(df[CQCLClean.services_offered]) > 1)
        | (df[CQCLClean.services_offered].isNull())
```

2024-07-18 14:32 UTC, MarionJHolloway commented on jobs/clean_cqc_location_data.py
> +        | (df[CQCLClean.services_offered].isNull())
Leaving this as is and changing tests for more clarity

2024-07-19 07:39 UTC, garypolzin commented on jobs/clean_cqc_location_data.py
> +        | (df[CQCLClean.services_offered].isNull())
yea happy to keep as it is, and this is also the benefit of the doc string isn't it!

2024-07-19 08:01 UTC, garypolzin approved these changes
looks great now thanks!

2024-07-19 08:12 UTC, merged