Refactor bed ratio
NMDSdevopsServiceAdm/DataEngineering pull request #512
Opened 2024-08-06 14:54 UTC by MarionJHolloway

# Description
Move bed ratio calculation out of cleaning function
Null bed ratio from a row when ascwds data is nulled

# How to test
Unit tests passing
Run in branch: https://eu-west-2.console.aws.amazon.com/states/home?region=eu-west-2#/v2/executions/details/arn:aws:states:eu-west-2:344210435447:execution:refactor-bed-ratio-Ind-CQC-Filled-Post-Estimates-Pipeline:36144089-0da5-4ae4-8b38-8373e4e87e05

# Developer checklist
- [x] Unit test
- [x] Linked to Trello ticket: https://trello.com/c/TjKmOh4c/712-refactor-move-creating-filled-post-per-bed-ratio-into-main-of-cleancqcindfilledposts-must
- [x] Documentation up to date

2024-08-08 14:29 UTC, garypolzin requested changes
Happy to approve if you don't think the suggestion is a good idea!

2024-08-08 14:29 UTC, garypolzin commented on tests/unit/test_ascwds_filtering_utils.py
> +        expected_df.show()
remove :)

2024-08-08 14:29 UTC, garypolzin commented on utils/ind_cqc_filled_posts_utils/null_ascwds_filled_post_outliers/ascwds_filtering_utils.py
> +    )
you could merge this code with the function calculate_filled_posts_per_bed_ratio in clean_ind_cqc_filled_posts so you give it the filled post column as an argument

in clean_ind_cqc_filled_posts it would become
`calculate_filled_posts_per_bed_ratio(df, IndCQC.ascwds_filled_posts_dedup)`

and this would be
`calculate_filled_posts_per_bed_ratio(df, IndCQC.ascwds_filled_posts_dedup_clean)`

we tend to use `carehome=Y` instead of `!= PrimaryServiceType.non_residential` - just incase we add more primary service types (we have 6 in our spss process, only 3 in AWS so far)

2024-08-08 14:34 UTC, MarionJHolloway commented on utils/ind_cqc_filled_posts_utils/null_ascwds_filled_post_outliers/ascwds_filtering_utils.py
> +    )
Yeah, that would be neater. I'll switch that out and move the function

2024-08-08 15:11 UTC, garypolzin commented on tests/test_file_data.py
> +
one thing I forgot earlier, add None values into these tests for both beds and filled posts

these tests were originally for the care home filter and that dataframe was filtered to where beds and posts were >0 and non-null, but now they've moved to the whole file they'll need nulls adding

2024-08-09 08:16 UTC, garypolzin commented on jobs/clean_ind_cqc_filled_posts.py
> +    Add a column with the filled post per bed ratio for care homes.
optional suggestion - do we need to explain why filled_post_column is an argument?

2024-08-09 08:19 UTC, garypolzin commented on tests/unit/test_clean_ind_cqc_filled_posts.py
> +)
this is a random formatting change (assuming this was automated), wonder if we have different settings

2024-08-09 08:24 UTC, garypolzin approved these changes
forgot to change from Comment to Approve!

2024-08-09 08:43 UTC, merged

2024-08-09 09:57 UTC, MarionJHolloway commented on utils/ind_cqc_filled_posts_utils/null_ascwds_filled_post_outliers/ascwds_filtering_utils.py
> +    PrimaryServiceType,
Just realised I missed these comments - outlook only showed me "forgot to change from Comment to Approve!"! I'll do another PR in a minute to cover them

2024-08-09 10:20 UTC, MarionJHolloway commented on jobs/clean_ind_cqc_filled_posts.py
> +    Add a column with the filled post per bed ratio for care homes.
I don't think so? It just makes it more flexible?