Null 999 filled posts [WIP]
NMDSdevopsServiceAdm/DataEngineering pull request #540
Opened 2024-08-29 16:29 UTC by MarionJHolloway

# Description
Add filter to null locations which have 999 ascwds filled posts
Add unit tests

# How to test
Unit tests passing
Run in branch: https://eu-west-2.console.aws.amazon.com/states/home?region=eu-west-2#/v2/executions/details/arn:aws:states:eu-west-2:344210435447:execution:null-999-filled-posts-Ind-CQC-Filled-Post-Estimates-Pipeline:79e345eb-7335-429c-bb78-71a160879c08

# Developer checklist
- [x] Unit test
- [x] Linked to Trello ticket: https://trello.com/c/80m4h0h4/413-filtering-example-workplaces-entering-999
- [x] Documentation up to date

2024-08-30 08:00 UTC, garypolzin requested changes
couple of small tweaks on this, it's more of a rogue rule this one so think we need to make it a bit more explanatory as to why we're doing it

I'm also wondering if not just saying 999 is the right decision, or whether we say 999. This rule will only ever be in place specifically for 999 entries so do we need to make it generic?

2024-08-30 08:00 UTC, garypolzin commented on utils/ind_cqc_filled_posts_utils/null_ascwds_filled_post_outliers/null_filled_posts_where_locations_use_missing_data_code.py
> +    Null rows where locations have 999 in ascwds_filled_posts_dedup_clean.
maybe add a bit more info into the docsting for this as it's a bit more rogue
'999' is used elsewhere in ASCWDS to represent not known, That isn't the case for these variables, however upon investigation, all 999 entries at the time of investigation do not look to be an accurate reflection so we are removing them as DQ

2024-08-30 08:00 UTC, garypolzin commented on tests/unit/test_null_filled_posts_where_locations_use_missing_data_code.py
> +        )
add a test that missing code is 999, just in case someone changes it by accident

2024-08-30 08:00 UTC, garypolzin commented on utils/ind_cqc_filled_posts_utils/null_ascwds_filled_post_outliers/null_filled_posts_where_locations_use_missing_data_code.py
> +MISSING_DATA_CODE = 999.0
just wondering if there's a clearer name for this, 999 isn't actually the missing data code they should use (it should be -1 or -2), we just suspect that some are using this

proxy_missing_data_code / user_inputted_missing_data_code / invalid_missing_data_code

2024-08-30 08:00 UTC, garypolzin commented on utils/ind_cqc_filled_posts_utils/null_ascwds_filled_post_outliers/null_filled_posts_where_locations_use_missing_data_code.py
> +MISSING_DATA_CODE = 999.0
do we need an explanation next to this 999 to say why it's 999, or possibly move it inside the function which calls it as it's already described in there?

2024-08-30 08:00 UTC, garypolzin commented on utils/column_values/categorical_column_values.py
> +    contained_missing_data_code: str = "contained_missing_data_code"
you might see this before the other comment but change this if we rename

2024-08-30 11:05 UTC, MarionJHolloway commented on utils/ind_cqc_filled_posts_utils/null_ascwds_filled_post_outliers/null_filled_posts_where_locations_use_missing_data_code.py
> +MISSING_DATA_CODE = 999.0
I can't move this into the function and still be able to test the value (as it will only exist when the function runs). I've added a brief comment instead.

2024-09-02 09:55 UTC, garypolzin requested changes
feel free to push back on adding 'invalid' to all the different places it should appear but it'd be good for everything to be consistent and more explanatory

2024-09-02 09:55 UTC, garypolzin commented on utils/ind_cqc_filled_posts_utils/null_ascwds_filled_post_outliers/null_filled_posts_where_locations_use_missing_data_code.py
> +    '999' is used elsewhere in ASCWDS to represent not known. Whilst that isn't the case for filled posts (i.e. the raw variables total staff and worker records), upon investigation, all 999 entries
remove `and worker records` from inside the brackets, this is only relevant for totalstaff
(they wouldn't enter 999 individual worker records to imply they don't know, they'd just type '999' into total staff)

2024-09-02 09:55 UTC, garypolzin commented on tests/unit/test_null_filled_posts_where_locations_use_missing_data_code.py
> +class MissingDataCodeTests(NullFilledPostsUsingMissingDataCodeTests):
update file names (job and test), this class and function name to be 'invalid' missing data code so it all aligns

2024-09-03 08:53 UTC, merged