WIP - Windsorize care home outliers
NMDSdevopsServiceAdm/DataEngineering pull request #545
Opened 2024-09-05 15:57 UTC by garypolzin

# Description
Previously we nulled outliers but this job now winsorizes outliers at the min/max permitted ratios

# How to test
Pipeline hasn't been run yet

[Trello](https://trello.com/c/Lphwopon/760-care-home-filtering-winsorizing-outliers)

# Developer checklist
- [X] Unit test
- [X] Linked to Trello ticket
- [X] Documentation up to date

2024-09-06 08:11 UTC, MarionJHolloway requested changes
This is really hard to review given the size of the PR. Can we split it into two? One for renaming (which is easy to approve) and then another one which will then make the changes you've made more obvious? 

I have made some comments on what I think is the main point of this PR, but I'm not confident on what I'm actually supposed to be checking her because it's flagging everything as new!

2024-09-06 08:11 UTC, MarionJHolloway commented on utils/ind_cqc_filled_posts_utils/clean_ascwds_filled_post_outliers/winsorize_care_home_filled_posts_per_bed_ratio_outliers.py
> +    # TODO: do we want to identify which values have been winsorized? how?
Yes, I think so and the branch is currently failing on this. Can we just use the same conditions as in the function winsorise outliers?

2024-09-06 08:11 UTC, MarionJHolloway commented on utils/ind_cqc_filled_posts_utils/clean_ascwds_filled_post_outliers/winsorize_care_home_filled_posts_per_bed_ratio_outliers.py
> +def select_data_not_in_subset_df(
Missing docstring

2024-09-06 08:11 UTC, MarionJHolloway commented on utils/ind_cqc_filled_posts_utils/clean_ascwds_filled_post_outliers/winsorize_care_home_filled_posts_per_bed_ratio_outliers.py
> +def create_banded_bed_count_column(
Missing doc string

2024-09-06 08:11 UTC, MarionJHolloway commented on utils/ind_cqc_filled_posts_utils/clean_ascwds_filled_post_outliers/winsorize_care_home_filled_posts_per_bed_ratio_outliers.py
> +def calculate_average_filled_posts_per_banded_bed_count(
Missing doc string

2024-09-06 08:11 UTC, MarionJHolloway commented on utils/ind_cqc_filled_posts_utils/clean_ascwds_filled_post_outliers/winsorize_care_home_filled_posts_per_bed_ratio_outliers.py
> +def calculate_expected_filled_posts_based_on_number_of_beds(
Missing doc string

2024-09-06 08:11 UTC, MarionJHolloway commented on utils/ind_cqc_filled_posts_utils/clean_ascwds_filled_post_outliers/winsorize_care_home_filled_posts_per_bed_ratio_outliers.py
> +        NumericalValues.MINIMUM_PERMITTED_UPPER_RATIO_CUTOFF,
Is this not the Max permitted? Might just need to rename function and magic number here

2024-09-06 08:11 UTC, MarionJHolloway commented on utils/ind_cqc_filled_posts_utils/clean_ascwds_filled_post_outliers/winsorize_care_home_filled_posts_per_bed_ratio_outliers.py
> +    lower_bound_condition = F.col(IndCQC.filled_posts_per_bed_ratio) < F.col(
If using these for filtering column, will need to abstract - could go in dataclass at the top for ease of ref?

2024-09-09 08:07 UTC, garypolzin commented on utils/ind_cqc_filled_posts_utils/clean_ascwds_filled_post_outliers/winsorize_care_home_filled_posts_per_bed_ratio_outliers.py
> +        NumericalValues.MINIMUM_PERMITTED_UPPER_RATIO_CUTOFF,
it's the mimimum permitted upper cutoff

we set this at 5

if the top 2.5% cutoff is calculated at 3.5, we would replace 3.5 with 5
if the top 2.5% cutoff is calculated at 18, we would use 18 as it's above the minimum permitted 5

2024-09-09 09:47 UTC, garypolzin commented on utils/ind_cqc_filled_posts_utils/clean_ascwds_filled_post_outliers/winsorize_care_home_filled_posts_per_bed_ratio_outliers.py
> +    # TODO: do we want to identify which values have been winsorized? how?
created a trello ticket for this

https://trello.com/c/kp8RLn7V/768-identify-values-changed-by-filtering-winsorizing

2024-09-09 10:20 UTC, MarionJHolloway approved these changes
Just a couple of small tweaks - have approved so I don't slow you down. Looks good though!

2024-09-09 10:20 UTC, MarionJHolloway commented on tests/test_file_data.py
> +        ("01", date(2023, 1, 1), "Y", PrimaryServiceType.care_home_only, 50, 2.0, 2.0, 0.04),
Can you leave the filtering rule column in, but not updated? I can pick up the ticket to fix this next. And maybe add a comment after the ones that should have changed?

2024-09-09 10:20 UTC, MarionJHolloway commented on utils/ind_cqc_filled_posts_utils/clean_ascwds_filled_post_outliers/winsorize_care_home_filled_posts_per_bed_ratio_outliers.py
> +        MINIMUM_PERMITTED_UPPER_RATIO_CUTOFF (float): Sets the lowest maximum filled_posts_per_bed_ratio permitted
I'm not sure where the comment you made has gone, but could you add the explanation here as to why this shouldn't be the max?

2024-09-09 10:32 UTC, garypolzin commented on utils/ind_cqc_filled_posts_utils/clean_ascwds_filled_post_outliers/winsorize_care_home_filled_posts_per_bed_ratio_outliers.py
> +        MINIMUM_PERMITTED_UPPER_RATIO_CUTOFF (float): Sets the lowest maximum filled_posts_per_bed_ratio permitted
your previous comment was where this value is used (not here where it's defined) so it's still there but further down :)

2024-09-09 11:59 UTC, merged