Add imputation gary
NMDSdevopsServiceAdm/DataEngineering pull request #585
Opened 2024-10-14 14:28 UTC by garypolzin

# Description
Imputation now outputs one column which is a combination of known data, extrapolated and interpolated data - the column name created contains the columns on the data used to create it.

# How to test
Data check running in branch - compare to previous outputs.
Check what happens to locations who switch between CH and NR.

[Trello ticket](https://trello.com/c/o0jObcV4/802-replace-current-extrap-interp-with-new-combined-version-in-the-pipeline)

# Developer checklist
- [X] Unit test
- [X] Linked to Trello ticket
- [X] Documentation up to date

2024-10-14 15:09 UTC, MarionJHolloway requested changes
A few bits to check and reword, but generally looking really good, well done!

Don't forget to rename you're PR as well ;)

2024-10-14 15:09 UTC, MarionJHolloway commented on tests/test_file_data.py
> +    split_dataset_rows = [
I think there's more rows of data here than you need? You really just need 4, to cover all the permutations of the filter you are using.

2024-10-14 15:09 UTC, MarionJHolloway commented on utils/estimate_filled_posts/models/imputation_with_extrapolation_and_interpolation.py
> +    True if there is at least one non-null value for the location, and False otherwise.
Could you add in "at any point in time" just for clarity.

2024-10-14 15:21 UTC, garypolzin commented on jobs/estimate_missing_ascwds_ind_cqc_filled_posts.py
>  from utils.estimate_filled_posts.models.interpolation import model_interpolation
Yea they still need doing, separate PR for those :)

2024-10-14 15:34 UTC, garypolzin commented on utils/column_names/ind_cqc_pipeline_columns.py
> +    imputation_posts_per_bed_ratio_rolling_average_model_filled_posts_per_bed_ratio: (
@MarionJHolloway I don't think so unfortunately, unless we rename the original column names

interpolation includes the column name which contains nulls and the model it uses to trend against
the column name is `filled_posts_per_bed_ratio`
the model name is `rolling_average_model_filled_posts_per_bed_ratio`

later on we'll impute `filled_posts_per_bed_ratio` using `care_home_model` so can't drop the model name as won't be able to tell the difference

or we just name ourselves, but still, it's imputing the `filled_posts_per_bed_ratio` using the `rolling_average_model_filled_posts_per_bed_ratio` model

2024-10-14 15:35 UTC, garypolzin commented on tests/test_file_data.py
> +    split_dataset_rows = [
Reduced to 8 rows
1-001 = interpolation (needs 2 known points and one null in between)
1-002 = extrapolation (one known, one null either side)
1-003 = no data

2024-10-14 15:36 UTC, garypolzin commented on tests/test_file_data.py
> +    split_dataset_rows = [
oh I've looked at the wrong dataset!

2024-10-14 15:38 UTC, MarionJHolloway commented on tests/test_file_data.py
> +    split_dataset_rows = [
I meant the test data for splitting the dataset - there's no imputation in that function?

2024-10-14 15:40 UTC, garypolzin commented on tests/test_file_data.py
> +    split_dataset_rows = [
Take 2

Yea 4 rows is fine now - previously the 'identify_locations_with_a_non_null_submission' function was inside this one which complicated the tests but I moved it outside for simplification, but then didn't simplify the test data!

2024-10-14 15:41 UTC, MarionJHolloway commented on utils/column_names/ind_cqc_pipeline_columns.py
> +    imputation_posts_per_bed_ratio_rolling_average_model_filled_posts_per_bed_ratio: (
Well you have "imputation filled posts rolling average_model" for non res, so could it just be "imputation posts per bed ratio rolling average model" for care homes?

2024-10-14 15:46 UTC, garypolzin commented on utils/column_names/ind_cqc_pipeline_columns.py
> +    imputation_posts_per_bed_ratio_rolling_average_model_filled_posts_per_bed_ratio: (
there are two models, a filled post on called `rolling_average_model` and another ratio one called `rolling_average_model_filled_posts_per_bed_ratio`

2024-10-14 15:47 UTC, garypolzin commented on utils/column_names/ind_cqc_pipeline_columns.py
> +    imputation_posts_per_bed_ratio_rolling_average_model_filled_posts_per_bed_ratio: (
"imputation posts per bed ratio rolling average model" implies we've used `rolling_average_model` as the basis for imputation

2024-10-14 15:53 UTC, MarionJHolloway commented on utils/column_names/ind_cqc_pipeline_columns.py
> +    imputation_posts_per_bed_ratio_rolling_average_model_filled_posts_per_bed_ratio: (
Could we dial it back further and just call them "imputation non res" and "imputation care homes"?

2024-10-15 07:06 UTC, garypolzin commented on utils/column_names/ind_cqc_pipeline_columns.py
> +    imputation_posts_per_bed_ratio_rolling_average_model_filled_posts_per_bed_ratio: (
I don't think so, in the final estimates model we currently have `extrapolation_rolling_average_model` and `extrapolation_non_res_with_dormancy_model` which are both non res but different models

could probably get rid of the column with null names so it does what extrapolation does now. so it won't say whether it's imputing posts or ratio, it'll just say which model it used

2024-10-15 08:06 UTC, MarionJHolloway approved these changes
Looks good!

2024-10-15 08:07 UTC, merged