Create archiving job
NMDSdevopsServiceAdm/DataEngineering pull request #616
Opened 2024-10-31 14:01 UTC by MarionJHolloway

# Description
Set up template for job and tests
Terraform job and add to pipeline

# How to test
Unit tests passing
Branch run: https://eu-west-2.console.aws.amazon.com/states/home?region=eu-west-2#/v2/executions/details/arn:aws:states:eu-west-2:344210435447:execution:create-archiving-job-Ind-CQC-Filled-Post-Estimates-Pipeline:cd29801f-0859-4089-9878-9d9f2f028c72

# Developer checklist
- [x] Unit test
- [x] Linked to Trello ticket: https://trello.com/c/pnQ6meKl/840-create-archive-file-for-estimates
- [x] Documentation up to date

2024-10-31 15:37 UTC, garypolzin requested changes
Couple of bits to look at, some of them questions :)

2024-10-31 15:37 UTC, garypolzin commented on terraform/pipeline/step-functions/IndCqcFilledPostEstimatePipeline-StepFunction.json
> +              "Next": "Run diagnotics and archive data"
amend spelling of diagnotics

2024-10-31 15:37 UTC, garypolzin commented on terraform/pipeline/step-functions/IndCqcFilledPostEstimatePipeline-StepFunction.json
> +                            }
'Validation and crawler' shouldn't start until 'filled posts by job role' are finished - one of the gold validations is for that job

2024-10-31 15:37 UTC, garypolzin commented on terraform/pipeline/glue.tf
> +    "--annual_filled_posts_archive_destination"  = "${module.datasets_bucket.bucket_uri}/domain=ind_cqc_filled_posts/dataset=annual_filled_posts_archive/"
do you think we create a new domain folder for archived/published figures

might make stuff easier to point at for those linking tableaus etc if the archived folder contains all the stuff we've published, less chance of linking to the wrong dataset hopefully

2024-10-31 15:58 UTC, MarionJHolloway commented on terraform/pipeline/glue.tf
> +    "--annual_filled_posts_archive_destination"  = "${module.datasets_bucket.bucket_uri}/domain=ind_cqc_filled_posts/dataset=annual_filled_posts_archive/"
We can also delete tables that we no longer use anymore and still keep the data in s3

2024-11-01 08:24 UTC, garypolzin requested changes
think the step function needs a little tweak but everything else looks good

2024-11-01 08:24 UTC, garypolzin commented on terraform/pipeline/step-functions/IndCqcFilledPostEstimatePipeline-StepFunction.json
> +                          "--annual_filled_posts_archive_destination": "${dataset_bucket_uri}/domain=ind_cqc_filled_posts/dataset=archived_annual_filled_posts/"
![image](https://github.com/user-attachments/assets/1efdd952-4670-420e-a382-b52ed835478e)

if the diagnostics job finishes before the archive job then the crawler won't run on the newly archived data

2024-11-01 08:30 UTC, garypolzin commented on terraform/pipeline/step-functions/IndCqcFilledPostEstimatePipeline-StepFunction.json
> +                          "--annual_filled_posts_archive_destination": "${dataset_bucket_uri}/domain=ind_cqc_filled_posts/dataset=archived_annual_filled_posts/"
actually come to think of it, do we want the archiving step as part of the main step function?
The archive is supposed to be copies of the published data so maybe for a while at least we specifically decide when to archive data

Otherwise if we run main several times a day for whatever reason then everyone of them goes into archive. Or if the first run of the month wasn't great, we tweak it and run again, then the 2nd run of the month is the archived version we want to use

if we do include in this pipeline, we'd want it to be after the gold validation (at the moment, we are archiving data regardless of whether there validation data issues or not)

2024-11-01 08:38 UTC, MarionJHolloway commented on terraform/pipeline/step-functions/IndCqcFilledPostEstimatePipeline-StepFunction.json
> +                          "--annual_filled_posts_archive_destination": "${dataset_bucket_uri}/domain=ind_cqc_filled_posts/dataset=archived_annual_filled_posts/"
Yeah, good point. I think if we rerun, especially early on, we probably want to store both sets of data temporarily, so maybe deleting the data we don't want afterwards would be best? I can add a timestamp column instead of date column as a partition so it will be easy to delete.

2024-11-01 08:46 UTC, garypolzin commented on terraform/pipeline/step-functions/IndCqcFilledPostEstimatePipeline-StepFunction.json
> +                          "--annual_filled_posts_archive_destination": "${dataset_bucket_uri}/domain=ind_cqc_filled_posts/dataset=archived_annual_filled_posts/"
I think the idea of the archived folder is that it's all data we've published

Your idea about saving files is a good one though, but I think that's a separate location - and that can be more short term, save all runs in the past month maybe? that way we can say 'the run from 3 days ago was better than this one so lets go back to that'

2024-11-01 08:48 UTC, garypolzin commented on terraform/pipeline/step-functions/IndCqcFilledPostEstimatePipeline-StepFunction.json
> +                          "--annual_filled_posts_archive_destination": "${dataset_bucket_uri}/domain=ind_cqc_filled_posts/dataset=archived_annual_filled_posts/"
the archived folder could even work from that location - the job becomes to copy run X into the archived folder

2024-11-01 14:16 UTC, garypolzin approved these changes

2024-11-01 14:20 UTC, merged