WIP - Add salary calculation function
NMDSdevopsServiceAdm/DataEngineering pull request #90
Opened 2022-06-27 15:15 UTC by LauraZM9

# Description
[[Epic1] PREP/TRANSFORM - Build salary calc functions](https://trello.com/c/3vxyr8WY)

# Developer checklist
- [ ] Unit test
- [ ] Linked to Trello ticket

2022-06-29 14:07 UTC, elcorbs reviewed
Few suggestions for refactoring the if statements and writing more tests. I realise that you might be limited in the tests based on the combinations of data you can preset using the data generation package. Maybe there's a way to set multiple scenarios out or you could call the function to generate the data in each test and pass in the values you want to give for those columns for the different scenarios.

2022-06-29 14:24 UTC, garypolzin requested changes

2022-06-29 14:24 UTC, garypolzin commented on tests/test_file_generator.py
> +        .withColumnSpec("hrlyrate", 100.5)
not sure what the best way of doing this is but it would be good to test the hours and pay rates for each eventuality, including some 'dodgy' ones where both `contracted_hrs` and `average_hrs` have been completed.

I've got quite a lot of mini test files in `test_ingest_cqc_care_directory` which do this sort of thing, instead of trying to create one file at the start which does everything

2022-06-29 14:24 UTC, garypolzin commented on jobs/prepare_workers.py
> +        return contracted_hrs
can you flip the order of these so we prioritise adding `contracted_hrs` over `average_hrs` please

2022-06-29 14:24 UTC, garypolzin commented on jobs/prepare_workers.py
> +                return None
the exception might capture this but the formula will only work correctly if `hrs_worked` is >0

2022-06-30 10:33 UTC, LauraZM9 commented on jobs/prepare_workers.py
> +                return None
Good point, Gary! The exception was only capturing if `hrs_worked` was 0.

2022-07-01 09:47 UTC, elcorbs approved these changes
Looks good!

2022-07-01 09:47 UTC, elcorbs commented on jobs/prepare_workers.py
> +    if row["emplstat"] in [192, 193, 194, 196]:
Can we have a comment here about what these numbers mean please.

2022-07-01 09:47 UTC, elcorbs commented on jobs/prepare_workers.py
> +        print("here", average_hrs)
Do you still need this print?

2022-07-04 15:05 UTC, garypolzin approved these changes

2022-07-04 15:20 UTC, merged